import { trapPilotCandidate } from './trap-pilot.candidate-builder';

export const TRAP_PILOT_OPEN_GAME_EXPANSION = [
  trapPilotCandidate({
    id: 'scholars-mate-qf3-d6-v1',
    title: 'Scholar\'s mate Qf3 route candidate',
    aliases: ['Scholar\'s mate, Qf3 route'],
    familyId: 'scholars-mate-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Bishop\'s Opening' },
    setupMoves: ['e2e4', 'e7e5', 'f1c4', 'b8c6', 'd1f3'],
    offer: {
      moveUci: 'd1f3',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White aligns the queen and bishop against f7 and leaves Black a natural-looking developing choice.',
    },
    response: {
      id: 'ignore-f7-with-d6',
      movesUci: ['d7d6'],
      explanation: 'Black reinforces e5 but does not address the immediate attack on f7.',
    },
    punishment: {
      lineUci: ['f3f7'],
      outcome: 'MATE',
      explanation: 'Qxf7 is mate because the queen is protected by the c4 bishop and the king has no legal escape.',
    },
    safeDefense: {
      moveUci: 'g8f6',
      explanation: 'Nf6 develops while directly covering h5 and blocking the queen route.',
    },
    summary: 'A second Scholar family occurrence with a distinct trigger position and Qf3 move order.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Scholar%27s_mate',
  }),
  trapPilotCandidate({
    id: 'legal-trap-natural-bh5-v1',
    title: 'Légal trap natural Bh5 route candidate',
    aliases: ['Légal mate, natural route'],
    familyId: 'legal-trap-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Philidor Defence' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'f1c4', 'd7d6', 'b1c3', 'c8g4', 'h2h3', 'g4h5', 'f3e5'],
    offer: {
      moveUci: 'f3e5',
      role: 'SACRIFICE',
      explanation: 'White offers the queen after provoking the pinning bishop onto h5.',
    },
    response: {
      id: 'bishop-takes-queen',
      movesUci: ['h5d1'],
      explanation: 'Black accepts the queen on d1 and abandons control of the mating squares.',
    },
    punishment: {
      lineUci: ['c4f7', 'e8e7', 'c3d5'],
      outcome: 'MATE',
      explanation: 'Bxf7+, Ke7 and Nd5 complete the three-minor-piece mating pattern.',
    },
    safeDefense: {
      moveUci: 'd6e5',
      explanation: 'dxe5 removes the advanced knight instead of accepting the queen.',
    },
    summary: 'A natural Légal move order kept separate from the existing g6 seed occurrence.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Legal_Trap',
  }),
  trapPilotCandidate({
    id: 'greco-center-queen-capture-v1',
    title: 'Greco center-attack candidate',
    aliases: ['Greco\'s Trap'],
    familyId: 'greco-trap-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Italian Game' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'f1c4', 'c6d4', 'e1g1', 'd4f3', 'd1f3', 'd8f6', 'f3b3', 'g8e7', 'b1c3', 'c7c6', 'd2d4', 'e5d4', 'e4e5'],
    offer: {
      moveUci: 'e4e5',
      role: 'SACRIFICE',
      explanation: 'White advances e5 and permits the queen to capture the central pawn.',
    },
    response: {
      id: 'queen-takes-e5',
      movesUci: ['f6e5'],
      explanation: 'Black takes e5 and steps onto a forcing king attack.',
    },
    punishment: {
      lineUci: ['c4f7', 'e8d8', 'c1f4'],
      outcome: 'DECISIVE_EVAL',
      explanation: 'Bxf7+ displaces the king and Bf4 develops with tempo against the exposed queen and king.',
    },
    safeDefense: {
      moveUci: 'e7g6',
      explanation: 'Ng6 retreats the knight and avoids the immediate forcing check sequence.',
    },
    summary: 'A long Italian occurrence that exercises king displacement and development-with-tempo evidence targets.',
    discoveryRef: 'https://chesstrapguide.com/trap/grecos-trap/',
  }),
  trapPilotCandidate({
    id: 'fried-liver-kxf7-v1',
    title: 'Fried Liver king-hunt candidate',
    aliases: ['Fried Liver Attack'],
    familyId: 'fried-liver-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Two Knights Defence' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'f1c4', 'g8f6', 'f3g5', 'd7d5', 'e4d5', 'f6d5', 'g5f7'],
    offer: {
      moveUci: 'g5f7',
      role: 'SACRIFICE',
      explanation: 'White sacrifices the g5 knight on f7 to draw the king into the centre.',
    },
    response: {
      id: 'king-accepts-f7-knight',
      movesUci: ['e8f7'],
      explanation: 'Black captures on f7 and accepts an exposed-king position.',
    },
    punishment: {
      lineUci: ['d1f3', 'f7e6', 'b1c3'],
      outcome: 'DECISIVE_EVAL',
      explanation: 'Qf3+, Ke6 and Nc3 bring the queen and second knight into the king hunt.',
    },
    safeDefense: {
      moveUci: 'c6b4',
      explanation: 'Nb4 declines the sacrifice and creates counterplay against c2.',
    },
    summary: 'A canonical king-hunt occurrence whose objective setup and practical temptation require evidence.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Two_Knights_Defense#Fried_Liver_Attack',
  }),
  trapPilotCandidate({
    id: 'max-lange-qxf6-v1',
    title: 'Max Lange queen-capture candidate',
    aliases: ['Max Lange trap'],
    familyId: 'max-lange-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Max Lange Attack' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'f1c4', 'g8f6', 'd2d4', 'e5d4', 'e1g1', 'f8c5', 'e4e5', 'd7d5', 'e5f6', 'd5c4', 'f1e1', 'c8e6', 'f3g5'],
    offer: {
      moveUci: 'f3g5',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White places the knight on g5 and invites the queen to capture the advanced f6 pawn.',
    },
    response: {
      id: 'queen-captures-f6',
      movesUci: ['d8f6'],
      explanation: 'Black takes on f6 and allows a forcing knight capture on e6.',
    },
    punishment: {
      lineUci: ['g5e6', 'f7e6', 'd1h5'],
      outcome: 'DECISIVE_EVAL',
      explanation: 'Nxe6, fxe6 and Qh5+ open the king while recovering material with tempo.',
    },
    safeDefense: {
      moveUci: 'e8d7',
      explanation: 'Kd7 steps away from the e-file and avoids the queen-capture branch.',
    },
    summary: 'A forcing Max Lange occurrence separating the tempting queen capture from the resulting king exposure.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Max_Lange_Attack',
  }),
  trapPilotCandidate({
    id: 'stafford-bg5-queen-bait-v1',
    title: 'Stafford Bg5 queen-bait candidate',
    aliases: ['Stafford Gambit Bg5 trap'],
    familyId: 'stafford-gambit-family',
    side: 'BLACK',
    soundness: 'UNASSESSED',
    opening: { name: 'Petrov\'s Defence, Stafford Gambit' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'g8f6', 'f3e5', 'b8c6', 'e5c6', 'd7c6', 'd2d3', 'f8c5'],
    offer: {
      moveUci: 'f8c5',
      role: 'SACRIFICE',
      explanation: 'Black develops the bishop to c5, leaving the queen apparently vulnerable after Bg5.',
    },
    response: {
      id: 'bishop-takes-queen-line',
      movesUci: ['c1g5'],
      explanation: 'White pins on g5 and later accepts the queen on d8.',
    },
    punishment: {
      lineUci: ['f6e4', 'g5d8', 'c5f2', 'e1e2', 'c8g4'],
      outcome: 'MATE',
      explanation: 'Nxe4, Bxd8, Bxf2+, Ke2 and Bg4 produce the mating construction.',
    },
    safeDefense: {
      moveUci: 'f1e2',
      explanation: 'Be2 develops without entering the queen-bait sequence.',
    },
    summary: 'A Stafford occurrence built around accepting Black’s queen rather than the more common h-file attack.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Petrov%27s_Defence#Stafford_Gambit',
  }),
  trapPilotCandidate({
    id: 'vienna-copycat-qf6-v1',
    title: 'Vienna copycat queen-raid candidate',
    aliases: ['Vienna Game copycat trap'],
    familyId: 'vienna-copycat-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Vienna Game' },
    setupMoves: ['e2e4', 'e7e5', 'b1c3', 'b8c6', 'f1c4', 'f8c5', 'd1g4'],
    offer: {
      moveUci: 'd1g4',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White plays Qg4 and invites Black to mirror the queen development.',
    },
    response: {
      id: 'copy-with-qf6',
      movesUci: ['d8f6'],
      explanation: 'Black copies with Qf6 and permits a forcing knight jump and queen raid.',
    },
    punishment: {
      lineUci: ['c3d5', 'f6f2', 'e1d1', 'f2f1', 'c4f1'],
      outcome: 'MATERIAL',
      explanation: 'Nd5 attacks the queen; the subsequent checks end with Bxf1 capturing the invading queen.',
    },
    safeDefense: {
      moveUci: 'g7g6',
      explanation: 'g6 challenges the white queen without copying its placement.',
    },
    summary: 'A symmetry-breaking Vienna occurrence where mirrored development creates a tactical liability.',
    discoveryRef: 'https://chesstrapguide.com/trap/kutjanin-jakobjuk-vienna-trap/',
  }),
  trapPilotCandidate({
    id: 'damiano-g6-rook-capture-v1',
    title: 'Damiano rook-capture candidate',
    aliases: ['Damiano\'s Trap'],
    familyId: 'damiano-defence-trap-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Damiano Defence' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'f7f6', 'f3e5'],
    offer: {
      moveUci: 'f3e5',
      role: 'SACRIFICE',
      explanation: 'White offers the e5 knight after Black weakens the king with ...f6.',
    },
    response: {
      id: 'f-pawn-captures-e5',
      movesUci: ['f6e5'],
      explanation: 'Black accepts the knight and opens the queen-check diagonal.',
    },
    punishment: {
      lineUci: ['d1h5', 'g7g6', 'h5e5', 'd8e7', 'e5h8'],
      outcome: 'MATERIAL',
      explanation: 'Qh5+, g6, Qxe5+, Qe7 and Qxh8 win the rook after the king-side structure is compromised.',
    },
    safeDefense: {
      moveUci: 'd8e7',
      explanation: 'Qe7 declines the knight and supports the weakened king-side squares.',
    },
    summary: 'A longer Damiano occurrence ending in a rook capture rather than the shorter existing material line.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Damiano_Defence',
  }),
  trapPilotCandidate({
    id: 'ponziani-d6-knight-fork-v1',
    title: 'Ponziani d6 fork candidate',
    aliases: ['Ponziani opening trap'],
    familyId: 'ponziani-trap-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Ponziani Opening' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'c2c3', 'g8f6', 'd2d4', 'f6e4', 'd4d5', 'c6e7', 'f3e5'],
    offer: {
      moveUci: 'f3e5',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White centralizes the knight on e5 and invites a routine pawn challenge.',
    },
    response: {
      id: 'challenge-with-d6',
      movesUci: ['d7d6'],
      explanation: 'Black attacks the knight with ...d6 but permits a forcing bishop check and pawn clearance.',
    },
    punishment: {
      lineUci: ['f1b5', 'c7c6', 'd5c6', 'b7c6', 'e5c6'],
      outcome: 'MATERIAL',
      explanation: 'Bb5+, c6, dxc6, bxc6 and Nxc6 win material through the exposed king and fork.',
    },
    safeDefense: {
      moveUci: 'e7g6',
      explanation: 'Ng6 retreats the other knight and avoids opening the c6 target.',
    },
    summary: 'A compact Ponziani fork occurrence with a natural pawn-push temptation.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Ponziani_Opening',
  }),
  trapPilotCandidate({
    id: 'traxler-nxf7-counterattack-v1',
    title: 'Traxler Nxf7 counterattack candidate',
    aliases: ['Traxler Counterattack'],
    familyId: 'traxler-family',
    side: 'BLACK',
    soundness: 'UNASSESSED',
    opening: { name: 'Two Knights Defence, Traxler Counterattack' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'f1c4', 'g8f6', 'f3g5', 'f8c5'],
    offer: {
      moveUci: 'f8c5',
      role: 'SACRIFICE',
      explanation: 'Black develops to c5 and leaves f7 apparently available to the attacking knight.',
    },
    response: {
      id: 'knight-takes-f7',
      movesUci: ['g5f7'],
      explanation: 'White captures f7 and attacks the queen and rook.',
    },
    punishment: {
      lineUci: ['c5f2', 'e1f2', 'f6e4'],
      outcome: 'DECISIVE_EVAL',
      explanation: 'Bxf2+, Kxf2 and Nxe4+ expose the white king and recover central material with check.',
    },
    safeDefense: {
      moveUci: 'd2d3',
      explanation: 'd3 reinforces e4 and declines the f7 capture.',
    },
    summary: 'A counter-sacrifice occurrence where Black answers an attack on f7 by attacking f2.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Two_Knights_Defense#Traxler_Variation',
  }),
] as const;
