import { trapPilotCandidate } from './trap-pilot.candidate-builder';

export const TRAP_PILOT_POSITIONAL_CANDIDATES = [
  trapPilotCandidate({
    id: 'noahs-ark-c5-v1',
    title: "Noah's Ark bishop-trap candidate",
    aliases: ["Noah's Ark Trap"],
    familyId: 'noahs-ark-trap-family',
    side: 'BLACK',
    soundness: 'SOUND',
    opening: { eco: 'C70', name: 'Ruy Lopez' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'f1b5', 'a7a6', 'b5a4', 'd7d6', 'd2d4', 'b7b5', 'a4b3', 'c6d4', 'f3d4', 'e5d4', 'd1d4', 'c7c5'],
    offer: {
      moveUci: 'c7c5',
      role: 'BAIT',
      explanation: 'Black attacks the queen and begins the pawn net around the b3 bishop.',
    },
    response: {
      id: 'queen-centralizes-d5',
      movesUci: ['d4d5'],
      explanation: 'White keeps the queen active but permits the forcing bishop-trap construction.',
    },
    punishment: {
      lineUci: ['c8e6', 'd5c6', 'e6d7', 'c6d5', 'c5c4'],
      outcome: 'MATERIAL',
      explanation: 'The queen is driven while ...c4 completes the pawn cage around the b3 bishop.',
    },
    safeDefense: {
      moveUci: 'd4e3',
      explanation: 'White retreats the queen without allowing the same forcing tempo sequence.',
    },
    summary: 'A family-style piece-trap candidate based on a pawn cage rather than immediate tactics.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Ruy_Lopez%2C_Noah%27s_Ark_Trap',
  }),
  trapPilotCandidate({
    id: 'tarrasch-open-qd7-v1',
    title: 'Tarrasch Trap Open Defence candidate',
    aliases: ['Tarrasch Trap, Open Defence'],
    familyId: 'tarrasch-trap-family',
    side: 'WHITE',
    soundness: 'SOUND',
    opening: { eco: 'C80', name: 'Ruy Lopez, Open Defence' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'f1b5', 'a7a6', 'b5a4', 'g8f6', 'e1g1', 'f6e4', 'd2d4', 'b7b5', 'a4b3', 'd7d5', 'd4e5', 'c8e6', 'c2c3', 'f8e7', 'f1e1', 'e8g8', 'f3d4'],
    offer: {
      moveUci: 'f3d4',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White centralizes the knight and creates a tactical pin-and-overload possibility on e6 and e4.',
    },
    response: {
      id: 'queen-to-d7',
      movesUci: ['d8d7'],
      explanation: 'Black connects pieces but allows the e6 exchange to pin the recapturing queen.',
    },
    punishment: {
      lineUci: ['d4e6', 'd7e6', 'e1e4'],
      outcome: 'MATERIAL',
      explanation: 'White exchanges on e6 and then wins the exposed e4 knight with the rook.',
    },
    safeDefense: {
      moveUci: 'c6b8',
      explanation: 'Black retreats the knight without placing the queen on the vulnerable d7 square.',
    },
    summary: 'A pin-and-overload candidate in the Open Ruy Lopez.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Ruy_Lopez%2C_Tarrasch_Trap',
  }),
  trapPilotCandidate({
    id: 'tarrasch-steinitz-castle-v1',
    title: 'Tarrasch Trap Steinitz candidate',
    aliases: ['Tarrasch Trap, Steinitz Defence', 'Dresden Trap'],
    familyId: 'tarrasch-trap-family',
    side: 'WHITE',
    soundness: 'SOUND',
    opening: { eco: 'C62', name: 'Ruy Lopez, Steinitz Defence' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'f1b5', 'd7d6', 'd2d4', 'c8d7', 'b1c3', 'g8f6', 'e1g1', 'f8e7', 'f1e1'],
    offer: {
      moveUci: 'f1e1',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White reinforces e4 and invites natural castling before Black resolves the centre.',
    },
    response: {
      id: 'castle-into-pawn-loss',
      movesUci: ['e8g8'],
      explanation: 'Black castles and permits a forcing exchange sequence that loses the e5 pawn.',
    },
    punishment: {
      lineUci: ['b5c6', 'd7c6', 'd4e5', 'd6e5', 'd1d8', 'a8d8', 'f3e5'],
      outcome: 'MATERIAL',
      explanation: 'White exchanges defenders and wins the e5 pawn after the queen trade.',
    },
    safeDefense: {
      moveUci: 'e5d4',
      explanation: 'Black concedes the centre immediately instead of castling into the tactic.',
    },
    summary: 'A subtle centre-resolution candidate where the natural king-safety move is the temptation.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Ruy_Lopez%2C_Tarrasch_Trap',
  }),
  trapPilotCandidate({
    id: 'wurzburger-bishop-trap-v1',
    title: 'Würzburger Trap bishop-capture candidate',
    aliases: ['Würzburger Trap'],
    familyId: 'wurzburger-trap-family',
    side: 'WHITE',
    soundness: 'PLAYABLE_RISK',
    opening: { eco: 'C29', name: 'Vienna Gambit' },
    setupMoves: ['e2e4', 'e7e5', 'b1c3', 'g8f6', 'f2f4', 'd7d5', 'f4e5', 'f6e4', 'd2d3', 'd8h4', 'g2g3', 'e4g3', 'g1f3', 'h4h5', 'c3d5', 'c8g4', 'd5f4', 'g4f3', 'f4h5', 'f3d1', 'h2g3'],
    offer: {
      moveUci: 'h2g3',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White restores material and allows the bishop to take the c2 pawn.',
    },
    response: {
      id: 'bishop-takes-c2',
      movesUci: ['d1c2'],
      explanation: 'Black takes another pawn but places the bishop beyond its escape squares.',
    },
    punishment: {
      lineUci: ['b2b3'],
      outcome: 'MATERIAL',
      explanation: 'b3 traps the c2 bishop, which will be won by Kd2 or Rh2.',
    },
    safeDefense: {
      moveUci: 'd1g4',
      explanation: 'Black retreats the bishop along the open diagonal instead of taking c2.',
    },
    summary: 'A long forcing sequence ending in a positional bishop cage.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Vienna_Game%2C_W%C3%BCrzburger_Trap',
  }),
  trapPilotCandidate({
    id: 'halosar-nb5-v1',
    title: 'Halosar Trap candidate',
    aliases: ['Halosar Trap'],
    familyId: 'halosar-trap-family',
    side: 'WHITE',
    soundness: 'DUBIOUS',
    opening: { eco: 'D00', name: 'Blackmar–Diemer Gambit, Ryder Gambit' },
    setupMoves: ['d2d4', 'd7d5', 'e2e4', 'd5e4', 'b1c3', 'g8f6', 'f2f3', 'e4f3', 'd1f3', 'd8d4', 'c1e3', 'd4b4', 'e1c1'],
    offer: {
      moveUci: 'e1c1',
      role: 'BAIT',
      explanation: 'White castles into an apparent pin opportunity against the queen and rook alignment.',
    },
    response: {
      id: 'bishop-pins-queen',
      movesUci: ['c8g4'],
      explanation: 'Black develops with a pin but overlooks the Nb5 and Nxc7 mating threat.',
    },
    punishment: {
      lineUci: ['c3b5', 'b8a6', 'f3b7'],
      outcome: 'MATERIAL',
      explanation: 'White creates the c7 threat and then captures b7 with a decisive attack on the rook.',
    },
    safeDefense: {
      moveUci: 'b4a5',
      explanation: 'Black moves the queen away without committing the bishop to the tactical pin.',
    },
    summary: 'A dubious-gambit candidate with a castling offer and a dual-threat punishment.',
    discoveryRef: 'https://www.nsvg.nl/main/archief.php?file=178+20130920+opening+Openingsvalletjes.txt&hoofdrubriek=theorie&mapid=100&rubriek=opening',
  }),
] as const;
