import { trapPilotCandidate } from './trap-pilot.candidate-builder';

export const TRAP_PILOT_CLOSED_FLANK_EXPANSION = [
  trapPilotCandidate({
    id: 'gibaud-lazard-ne3-v1',
    title: 'Gibaud–Lazard Ne3 candidate',
    aliases: ['Gibaud–Lazard Trap'],
    familyId: 'gibaud-lazard-family',
    side: 'BLACK',
    soundness: 'UNASSESSED',
    opening: { name: 'Indian Game, Lazard Gambit' },
    setupMoves: ['d2d4', 'g8f6', 'b1d2', 'e7e5', 'd4e5', 'f6g4'],
    offer: {
      moveUci: 'f6g4',
      role: 'TACTICAL_PERMISSION',
      explanation: 'Black jumps to g4 and invites a natural pawn chase.',
    },
    response: {
      id: 'attack-knight-with-h3',
      movesUci: ['h2h3'],
      explanation: 'White attacks the knight but weakens control of e3.',
    },
    punishment: {
      lineUci: ['g4e3'],
      outcome: 'MATERIAL',
      explanation: 'Ne3 attacks the queen and c2 simultaneously, creating decisive material threats.',
    },
    safeDefense: {
      moveUci: 'g1f3',
      explanation: 'Nf3 develops and controls e5 and h4 without chasing the knight.',
    },
    summary: 'A minimal four-move trap occurrence useful for validating short trigger and punishment sequences.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Am%C3%A9d%C3%A9e_Gibaud',
  }),
  trapPilotCandidate({
    id: 'combe-hasenfuss-qa5-v1',
    title: 'Combe–Hasenfuss Qa5 candidate',
    aliases: ['Combe–Hasenfuss Trap'],
    familyId: 'combe-hasenfuss-family',
    side: 'BLACK',
    soundness: 'UNASSESSED',
    opening: { name: 'Old Benoni move order' },
    setupMoves: ['d2d4', 'c7c5', 'c2c4', 'c5d4', 'g1f3', 'e7e5'],
    offer: {
      moveUci: 'e7e5',
      role: 'TACTICAL_PERMISSION',
      explanation: 'Black advances e5 and leaves the pawn apparently capturable by the developed knight.',
    },
    response: {
      id: 'knight-captures-e5',
      movesUci: ['f3e5'],
      explanation: 'White takes e5 and overlooks the queen check along the fifth rank.',
    },
    punishment: {
      lineUci: ['d8a5', 'c1d2', 'a5e5'],
      outcome: 'MATERIAL',
      explanation: 'Qa5+, Bd2 and Qxe5 recover the pawn while winning the exposed knight.',
    },
    safeDefense: {
      moveUci: 'e2e3',
      explanation: 'e3 supports d4 and avoids the loose-knight capture.',
    },
    summary: 'A compact queen-check fork occurrence from a Benoni move order.',
    discoveryRef: 'https://en.wikipedia.org/wiki/List_of_chess_traps',
  }),
  trapPilotCandidate({
    id: 'levenfish-ne6-queen-trap-v1',
    title: 'Levenfish Ne6 queen-trap candidate',
    aliases: ['Levenfish Trap'],
    familyId: 'levenfish-trap-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Sicilian Defence, Dragon, Levenfish Attack' },
    setupMoves: ['e2e4', 'c7c5', 'g1f3', 'd7d6', 'd2d4', 'c5d4', 'f3d4', 'g8f6', 'b1c3', 'g7g6', 'f2f4', 'f8g7', 'e4e5'],
    offer: {
      moveUci: 'e4e5',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White advances e5 and invites Black to resolve the central tension with the d-pawn.',
    },
    response: {
      id: 'd-pawn-captures-e5',
      movesUci: ['d6e5'],
      explanation: 'Black captures e5 and permits a forcing check-and-fork sequence.',
    },
    punishment: {
      lineUci: ['f4e5', 'f6g4', 'f1b5', 'e8f8', 'd4e6'],
      outcome: 'MATERIAL',
      explanation: 'fxe5, Ng4, Bb5+, Kf8 and Ne6+ leave the black queen trapped or lost.',
    },
    safeDefense: {
      moveUci: 'f6h5',
      explanation: 'Nh5 preserves the knight and avoids opening the d6 square.',
    },
    summary: 'A Sicilian occurrence combining a bishop check with a knight fork against the queen.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Sicilian_Defence,_Levenfish_Variation',
  }),
  trapPilotCandidate({
    id: 'ruy-lopez-qd3-pawn-win-v1',
    title: 'Ruy Lopez Qd3 centre-resolution candidate',
    aliases: ['Ruy Lopez expert standby trap'],
    familyId: 'ruy-lopez-center-resolution-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Ruy Lopez, Old Steinitz Defence' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'f1b5', 'd7d6', 'd2d4', 'c8d7', 'b1c3', 'g8f6', 'd1d3'],
    offer: {
      moveUci: 'd1d3',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White places the queen on d3 and leaves Black a routine developing move.',
    },
    response: {
      id: 'develop-bishop-e7',
      movesUci: ['f8e7'],
      explanation: 'Black develops the bishop without first resolving the centre.',
    },
    punishment: {
      lineUci: ['b5c6', 'd7c6', 'd4e5', 'd6e5', 'f3e5'],
      outcome: 'MATERIAL',
      explanation: 'Bxc6, Bxc6, dxe5, dxe5 and Nxe5 win the central pawn through defender removal.',
    },
    safeDefense: {
      moveUci: 'e5d4',
      explanation: 'exd4 resolves the centre before completing development.',
    },
    summary: 'A quiet Ruy Lopez occurrence where a normal developing move loses a central pawn.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Ruy_Lopez',
  }),
  trapPilotCandidate({
    id: 'caro-kann-two-knights-nxf7-v1',
    title: 'Caro-Kann Two Knights Nxf7 candidate',
    aliases: ['Caro-Kann Two Knights trap'],
    familyId: 'caro-kann-two-knights-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Caro-Kann Defence, Two Knights' },
    setupMoves: ['e2e4', 'c7c6', 'b1c3', 'd7d5', 'g1f3', 'd5e4', 'c3e4', 'c8f5', 'e4g3', 'f5g6', 'h2h4', 'h7h6', 'f3e5', 'g6h7', 'd1h5', 'g7g6', 'f1c4', 'e7e6', 'h5e2'],
    offer: {
      moveUci: 'h5e2',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White retreats the queen to e2 while preserving pressure on e6 and f7.',
    },
    response: {
      id: 'develop-knight-f6',
      movesUci: ['g8f6'],
      explanation: 'Black develops naturally but permits a forcing knight sacrifice on f7.',
    },
    punishment: {
      lineUci: ['e5f7', 'e8f7', 'e2e6'],
      outcome: 'DECISIVE_EVAL',
      explanation: 'Nxf7, Kxf7 and Qxe6+ expose the king and recover material with check.',
    },
    safeDefense: {
      moveUci: 'b8a6',
      explanation: 'Na6 develops away from the vulnerable f7 complex.',
    },
    summary: 'A Caro-Kann occurrence included to broaden the corpus beyond open and gambit positions.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Caro%E2%80%93Kann_Defence',
  }),
  trapPilotCandidate({
    id: 'qga-greedy-b5-v1',
    title: 'Queen’s Gambit Accepted greedy-b5 candidate',
    aliases: ['QGA pawn-holding trap'],
    familyId: 'qga-greedy-pawn-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Queen\'s Gambit Accepted' },
    setupMoves: ['d2d4', 'd7d5', 'c2c4', 'd5c4', 'e2e4'],
    offer: {
      moveUci: 'e2e4',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White builds the e4 centre and leaves Black the option of trying to hold the c4 pawn.',
    },
    response: {
      id: 'defend-c4-with-b5',
      movesUci: ['b7b5'],
      explanation: 'Black advances b5 and commits additional tempi to keeping the extra pawn.',
    },
    punishment: {
      lineUci: ['a2a4', 'c7c6', 'a4b5', 'c6b5', 'b1c3', 'c8d7', 'b2b3'],
      outcome: 'POSITIONAL_BIND',
      explanation: 'a4, c6, axb5, cxb5, Nc3, Bd7 and b3 undermine the pawn chain and accelerate development.',
    },
    safeDefense: {
      moveUci: 'e7e5',
      explanation: 'e5 returns pressure to the centre instead of trying to hold c4.',
    },
    summary: 'A strategic trap occurrence where greed creates a vulnerable queenside chain rather than an immediate tactic.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Queen%27s_Gambit_Accepted',
  }),
  trapPilotCandidate({
    id: 'slav-bf5-qb3-v1',
    title: 'Slav early-Bf5 double-attack candidate',
    aliases: ['Slav Bf5 trap'],
    familyId: 'slav-bf5-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Slav Defence' },
    setupMoves: ['d2d4', 'd7d5', 'c2c4', 'c7c6', 'g1f3', 'g8f6', 'b1c3'],
    offer: {
      moveUci: 'b1c3',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White develops Nc3 and leaves the c8 bishop a natural active square.',
    },
    response: {
      id: 'develop-bishop-f5',
      movesUci: ['c8f5'],
      explanation: 'Black develops Bf5 before resolving the central tension.',
    },
    punishment: {
      lineUci: ['c4d5', 'c6d5', 'd1b3'],
      outcome: 'POSITIONAL_BIND',
      explanation: 'cxd5, cxd5 and Qb3 attack both b7 and d5, forcing an awkward concession.',
    },
    safeDefense: {
      moveUci: 'e7e6',
      explanation: 'e6 supports d5 before developing the bishop.',
    },
    summary: 'A short Slav occurrence based on a double attack rather than a forced material sequence.',
    discoveryRef: 'https://thechessworld.com/articles/openings/slav-defense-the-complete-guide/',
  }),
  trapPilotCandidate({
    id: 'alekhine-osullivan-queen-sac-v1',
    title: 'Alekhine O’Sullivan queen-sacrifice candidate',
    aliases: ['O\'Sullivan Gambit trap'],
    familyId: 'alekhine-osullivan-family',
    side: 'BLACK',
    soundness: 'UNASSESSED',
    opening: { name: 'Alekhine\'s Defence, O\'Sullivan Gambit' },
    setupMoves: ['e2e4', 'g8f6', 'e4e5', 'f6d5', 'd2d4', 'b7b5', 'f1b5', 'c7c5', 'c2c4', 'c5d4', 'd1d4', 'd5b4', 'b1a3', 'd8a5'],
    offer: {
      moveUci: 'd8a5',
      role: 'SACRIFICE',
      explanation: 'Black plays Qa5 and offers the queen after driving the white pieces into a loose configuration.',
    },
    response: {
      id: 'develop-bishop-d2',
      movesUci: ['c1d2'],
      explanation: 'White develops Bd2 and permits the queen sacrifice on a3.',
    },
    punishment: {
      lineUci: ['a5a3', 'b2a3', 'b4c2'],
      outcome: 'MATERIAL',
      explanation: 'Qxa3, bxa3 and Nc2+ fork the king and queen after the accepted sacrifice.',
    },
    safeDefense: {
      moveUci: 'd4d2',
      explanation: 'Qd2 consolidates the queen and bishop without accepting the sacrifice.',
    },
    summary: 'A queen-sacrifice occurrence from an Alekhine sideline, retained as unassessed pending engine evidence.',
    discoveryRef: 'https://www.houseofstaunton.com/blogs/chess-strategies/the-alekhine-defense',
  }),
  trapPilotCandidate({
    id: 'pirc-bxf7-nd5-v1',
    title: 'Pirc Bxf7 queen-confinement candidate',
    aliases: ['Pirc Bxf7 trap'],
    familyId: 'pirc-bxf7-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Pirc Defence' },
    setupMoves: ['d2d4', 'g8f6', 'b1c3', 'g7g6', 'e2e4', 'd7d6', 'g1f3', 'f8g7', 'f1c4', 'e8g8', 'c1f4', 'b8d7', 'e1g1'],
    offer: {
      moveUci: 'e1g1',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White castles while keeping the bishop and knights aimed at the black king.',
    },
    response: {
      id: 'rook-centralizes-e8',
      movesUci: ['f8e8'],
      explanation: 'Black plays Re8 and leaves f7 vulnerable to a forcing sacrifice.',
    },
    punishment: {
      lineUci: ['c4f7', 'g8f7', 'f3g5', 'f7g8', 'c3d5'],
      outcome: 'POSITIONAL_BIND',
      explanation: 'Bxf7, Kxf7, Ng5+, Kg8 and Nd5 create a fork-and-confinement structure around the queen.',
    },
    safeDefense: {
      moveUci: 'e7e6',
      explanation: 'e6 reinforces f7 and challenges the centre.',
    },
    summary: 'A Pirc occurrence whose final queen-confinement claim must be verified by engine evidence.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Pirc_Defence',
  }),
  trapPilotCandidate({
    id: 'cambridge-springs-bd3-v1',
    title: 'Cambridge Springs Bd3 candidate',
    aliases: ['Cambridge Springs Bd3 trap'],
    familyId: 'cambridge-springs-family',
    side: 'BLACK',
    soundness: 'UNASSESSED',
    opening: { name: 'Queen\'s Gambit Declined, Cambridge Springs' },
    setupMoves: ['d2d4', 'd7d5', 'c2c4', 'e7e6', 'b1c3', 'g8f6', 'c1g5', 'b8d7', 'e2e3', 'c7c6', 'g1f3', 'd8a5', 'f3d2', 'f8b4', 'd1c2', 'e8g8'],
    offer: {
      moveUci: 'e8g8',
      role: 'TACTICAL_PERMISSION',
      explanation: 'Black castles after pinning the c3 knight and pressuring the g5 bishop.',
    },
    response: {
      id: 'auto-develop-bishop-d3',
      movesUci: ['f1d3'],
      explanation: 'White develops Bd3 and overlooks the central capture sequence.',
    },
    punishment: {
      lineUci: ['d5c4', 'g5f6', 'c4d3', 'c2d3', 'd7f6'],
      outcome: 'MATERIAL',
      explanation: 'dxc4, Bxf6, cxd3, Qxd3 and Nxf6 win material while removing the pinned bishop.',
    },
    safeDefense: {
      moveUci: 'a2a3',
      explanation: 'a3 questions the b4 bishop before committing the f1 bishop.',
    },
    summary: 'A Cambridge Springs occurrence built around an automatic development mistake rather than the older Elephant motif.',
    discoveryRef: 'https://www.chessworld.net/cambridge-springs-defense.asp',
  }),
] as const;
