import { trapPilotCandidate } from './trap-pilot.candidate-builder';

export const TRAP_PILOT_MATING_CANDIDATES = [
  trapPilotCandidate({
    id: 'scholars-mate-qh5-v1',
    title: "Scholar's mate candidate",
    aliases: ["Scholar's mate"],
    familyId: 'scholars-mate-family',
    side: 'WHITE',
    soundness: 'PLAYABLE_RISK',
    opening: { eco: 'C20', name: "King's Pawn Game" },
    setupMoves: ['e2e4', 'e7e5', 'f1c4', 'b8c6', 'd1h5'],
    offer: {
      moveUci: 'd1h5',
      role: 'BAIT',
      explanation: 'White creates the direct Qxf7 mate threat and invites a natural developing move that ignores it.',
    },
    response: {
      id: 'ignore-f7-threat',
      movesUci: ['g8f6'],
      explanation: 'Black develops the knight but leaves f7 undefended against the queen and bishop.',
    },
    punishment: {
      lineUci: ['h5f7'],
      outcome: 'MATE',
      explanation: 'Qxf7 is checkmate in the concrete position.',
    },
    safeDefense: {
      moveUci: 'g7g6',
      explanation: 'Black attacks the queen and prevents the immediate mating capture.',
    },
    summary: 'A minimal mate threat candidate used to validate one-move temptation and punishment.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Scholar%27s_mate',
  }),
  trapPilotCandidate({
    id: 'fools-mate-e5-v1',
    title: "Fool's mate candidate",
    aliases: ["Fool's mate"],
    familyId: 'fools-mate-family',
    side: 'BLACK',
    soundness: 'SOUND',
    opening: { eco: 'A00', name: 'Irregular opening sequence' },
    setupMoves: ['f2f3', 'e7e5'],
    offer: {
      moveUci: 'e7e5',
      role: 'TACTICAL_PERMISSION',
      explanation: 'Black opens the queen diagonal while White has already weakened the king.',
    },
    response: {
      id: 'weaken-g-pawn',
      movesUci: ['g2g4'],
      explanation: 'White opens the h4-e1 diagonal completely.',
    },
    punishment: {
      lineUci: ['d8h4'],
      outcome: 'MATE',
      explanation: 'Qh4 is immediate checkmate.',
    },
    safeDefense: {
      moveUci: 'e2e4',
      explanation: 'White occupies the centre without opening the mating diagonal further.',
    },
    summary: 'A baseline forced-mate occurrence with no material bait.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Fool%27s_mate',
  }),
  trapPilotCandidate({
    id: 'englund-qb2-mate-v1',
    title: 'Englund Gambit queen-side mate candidate',
    aliases: ['Englund Gambit trap'],
    familyId: 'englund-gambit-trap-family',
    side: 'BLACK',
    soundness: 'DUBIOUS',
    opening: { eco: 'A40', name: 'Englund Gambit' },
    setupMoves: ['d2d4', 'e7e5', 'd4e5', 'b8c6', 'g1f3', 'd8e7', 'c1f4', 'e7b4', 'f4d2', 'b4b2'],
    offer: {
      moveUci: 'b4b2',
      role: 'BAIT',
      explanation: 'Black takes b2 and invites the bishop to attack the queen.',
    },
    response: {
      id: 'chase-queen-with-bishop',
      movesUci: ['d2c3'],
      explanation: 'White develops with tempo but blocks the c-file mating square structure.',
    },
    punishment: {
      lineUci: ['f8b4', 'd1d2', 'b4c3', 'd2c3', 'b2c1'],
      outcome: 'MATE',
      explanation: 'The bishop deflection allows Qc1 mate after the queen recapture.',
    },
    safeDefense: {
      moveUci: 'b1c3',
      explanation: 'White develops the knight and protects the rook without entering the mating pattern.',
    },
    summary: 'A dubious-opening candidate that separates practical trap value from objective soundness.',
    discoveryRef: 'https://www.chessreps.com/opening/englund-gambit',
  }),
  trapPilotCandidate({
    id: 'siberian-ng4-v1',
    title: 'Siberian Trap candidate',
    aliases: ['Siberian Trap'],
    familyId: 'siberian-trap-family',
    side: 'BLACK',
    soundness: 'PLAYABLE_RISK',
    opening: { eco: 'B20', name: 'Smith–Morra Gambit' },
    setupMoves: ['e2e4', 'c7c5', 'd2d4', 'c5d4', 'c2c3', 'd4c3', 'b1c3', 'b8c6', 'g1f3', 'e7e6', 'f1c4', 'd8c7', 'e1g1', 'g8f6', 'd1e2', 'f6g4'],
    offer: {
      moveUci: 'f6g4',
      role: 'BAIT',
      explanation: 'Black places the knight near h2 and invites a routine pawn chase.',
    },
    response: {
      id: 'chase-g4-knight',
      movesUci: ['h2h3'],
      explanation: 'White attacks the knight but overlooks the d4 deflection and h2 mating route.',
    },
    punishment: {
      lineUci: ['c6d4', 'f3d4', 'c7h2'],
      outcome: 'MATE',
      explanation: 'The knight deflection clears Qh2 mate.',
    },
    safeDefense: {
      moveUci: 'c3b5',
      explanation: 'White creates counterplay against c7 instead of weakening h2.',
    },
    summary: 'A multi-move tactical trap with a natural pawn-chase temptation.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Sicilian_Defence%2C_Smith%E2%80%93Morra_Gambit%2C_Siberian_Trap',
  }),
  trapPilotCandidate({
    id: 'kieninger-smothered-mate-v1',
    title: 'Kieninger Trap candidate',
    aliases: ['Kieninger Trap'],
    familyId: 'kieninger-trap-family',
    side: 'BLACK',
    soundness: 'PLAYABLE_RISK',
    opening: { eco: 'A52', name: 'Budapest Gambit' },
    setupMoves: ['d2d4', 'g8f6', 'c2c4', 'e7e5', 'd4e5', 'f6g4', 'c1f4', 'b8c6', 'g1f3', 'f8b4', 'b1d2', 'd8e7', 'a2a3', 'g4e5'],
    offer: {
      moveUci: 'g4e5',
      role: 'TACTICAL_PERMISSION',
      explanation: 'Black recovers the pawn while apparently leaving the b4 bishop en prise.',
    },
    response: {
      id: 'capture-b4-bishop',
      movesUci: ['a3b4'],
      explanation: 'White takes the bishop but removes the a-pawn guard from the d3 mating square pattern.',
    },
    punishment: {
      lineUci: ['e5d3'],
      outcome: 'MATE',
      explanation: 'Nd3 is smothered mate.',
    },
    safeDefense: {
      moveUci: 'f3e5',
      explanation: 'White exchanges the active knight instead of taking the bishop immediately.',
    },
    summary: 'A one-move smothered-mate candidate that stresses legal side-to-move identity.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Budapest_Gambit#Kieninger_Trap',
  }),
  trapPilotCandidate({
    id: 'tennison-queen-skewer-v1',
    title: 'Tennison Gambit queen-skewer candidate',
    aliases: ['Tennison Gambit ICBM pattern'],
    familyId: 'tennison-gambit-family',
    side: 'WHITE',
    soundness: 'DUBIOUS',
    opening: { eco: 'A06', name: 'Tennison Gambit' },
    setupMoves: ['g1f3', 'd7d5', 'e2e4', 'd5e4', 'f3g5', 'g8f6', 'd2d3', 'e4d3', 'f1d3', 'h7h6', 'g5f7'],
    offer: {
      moveUci: 'g5f7',
      role: 'SACRIFICE',
      explanation: 'White forks queen and rook and invites the king to capture the knight.',
    },
    response: {
      id: 'king-captures-f7',
      movesUci: ['e8f7'],
      explanation: 'Black accepts the knight and steps onto the bishop-check line.',
    },
    punishment: {
      lineUci: ['d3g6', 'f7g6', 'd1d8'],
      outcome: 'MATERIAL',
      explanation: 'The bishop sacrifice deflects the king and allows White to take the queen.',
    },
    safeDefense: {
      moveUci: 'd8d5',
      explanation: 'Black moves the attacked queen instead of accepting the sacrificial knight.',
    },
    summary: 'A dubious gambit candidate ending in a queen loss rather than mate.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Tennison_Gambit',
  }),
] as const;
