import { trapPilotCandidate } from './trap-pilot.candidate-builder';

export const TRAP_PILOT_GAMBIT_EXPANSION = [
  trapPilotCandidate({
    id: 'monticelli-bxg2-mate-v1',
    title: 'Monticelli diagonal-mate candidate',
    aliases: ['Monticelli Trap'],
    familyId: 'monticelli-trap-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Bogo-Indian Defence' },
    setupMoves: ['d2d4', 'g8f6', 'c2c4', 'e7e6', 'g1f3', 'f8b4', 'c1d2', 'b4d2', 'd1d2', 'b7b6', 'g2g3', 'c8b7', 'f1g2', 'e8g8', 'b1c3', 'f6e4', 'd2c2', 'e4c3', 'f3g5'],
    offer: {
      moveUci: 'f3g5',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White places the knight on g5, leaving the g2 bishop apparently capturable.',
    },
    response: {
      id: 'bishop-captures-g2',
      movesUci: ['b7g2'],
      explanation: 'Black follows the long diagonal and takes the g2 bishop.',
    },
    punishment: {
      lineUci: ['c2h7'],
      outcome: 'MATE',
      explanation: 'Qxh7 is mate because the queen and knight cover the king-side escape squares.',
    },
    safeDefense: {
      moveUci: 'h7h6',
      explanation: 'h6 removes the advanced knight before accepting material.',
    },
    summary: 'A Bogo-Indian mating occurrence based on clearing the queen’s path to h7.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Bogo-Indian_Defence%2C_Monticelli_Trap',
  }),
  trapPilotCandidate({
    id: 'fajarowicz-nxf2-queen-win-v1',
    title: 'Fajarowicz Nxf2 deflection candidate',
    aliases: ['Fajarowicz Trap'],
    familyId: 'fajarowicz-trap-family',
    side: 'BLACK',
    soundness: 'UNASSESSED',
    opening: { name: 'Budapest Gambit, Fajarowicz Variation' },
    setupMoves: ['d2d4', 'g8f6', 'c2c4', 'e7e5', 'd4e5', 'f6e4', 'g1f3', 'b8c6', 'a2a3', 'd7d6', 'e5d6', 'f8d6'],
    offer: {
      moveUci: 'f8d6',
      role: 'TACTICAL_PERMISSION',
      explanation: 'Black develops the bishop to d6 and leaves White a natural kingside fianchetto.',
    },
    response: {
      id: 'play-g3',
      movesUci: ['g2g3'],
      explanation: 'White plays g3 and permits the knight sacrifice on f2.',
    },
    punishment: {
      lineUci: ['e4f2', 'e1f2', 'd6g3', 'f2g3', 'd8d1'],
      outcome: 'MATERIAL',
      explanation: 'Nxf2, Kxf2, Bxg3+, Kxg3 and Qxd1 win the queen through king deflection.',
    },
    safeDefense: {
      moveUci: 'e2e3',
      explanation: 'e3 develops while keeping f2 defended by the king and queen structure.',
    },
    summary: 'A queen-loss occurrence that stresses multi-stage king deflection.',
    discoveryRef: 'https://chesstrapguide.com/learn/fajarowicz-trap-guide/',
  }),
  trapPilotCandidate({
    id: 'budapest-adler-nd3-mate-v1',
    title: 'Budapest Adler Nd3 mate candidate',
    aliases: ['Budapest Gambit trap'],
    familyId: 'budapest-gambit-trap-family',
    side: 'BLACK',
    soundness: 'UNASSESSED',
    opening: { name: 'Budapest Gambit' },
    setupMoves: ['d2d4', 'g8f6', 'c2c4', 'e7e5', 'd4e5', 'f6g4', 'c1f4', 'b8c6', 'g1f3', 'f8b4', 'b1d2', 'd8e7', 'a2a3', 'g4e5'],
    offer: {
      moveUci: 'g4e5',
      role: 'TACTICAL_PERMISSION',
      explanation: 'Black recovers on e5 while leaving the b4 bishop apparently en prise.',
    },
    response: {
      id: 'a-pawn-captures-bishop',
      movesUci: ['a3b4'],
      explanation: 'White captures the bishop with the a-pawn and removes a key guard from d3.',
    },
    punishment: {
      lineUci: ['e5d3'],
      outcome: 'MATE',
      explanation: 'Nd3 is a smothered mating move in the concrete position.',
    },
    safeDefense: {
      moveUci: 'f3e5',
      explanation: 'Nxe5 exchanges the active knight instead of taking the bishop.',
    },
    summary: 'A Budapest occurrence related to, but positionally distinct from, the existing Kieninger seed.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Budapest_Gambit',
  }),
  trapPilotCandidate({
    id: 'halloween-central-chase-v1',
    title: 'Halloween central-chase candidate',
    aliases: ['Halloween Gambit'],
    familyId: 'halloween-gambit-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Four Knights Game, Halloween Gambit' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'b1c3', 'g8f6', 'f3e5'],
    offer: {
      moveUci: 'f3e5',
      role: 'SACRIFICE',
      explanation: 'White sacrifices the f3 knight on e5 to gain tempi against the remaining black knight.',
    },
    response: {
      id: 'accept-e5-knight',
      movesUci: ['c6e5'],
      explanation: 'Black accepts the sacrificed knight and enters the central pawn chase.',
    },
    punishment: {
      lineUci: ['d2d4', 'e5c6', 'd4d5', 'c6e5', 'f2f4', 'e5g6', 'e4e5'],
      outcome: 'POSITIONAL_BIND',
      explanation: 'd4, d5, f4 and e5 drive the knight repeatedly while White builds a broad centre.',
    },
    safeDefense: {
      moveUci: 'f6g8',
      explanation: 'Ng8 declines the sacrifice and preserves material without entering the chase.',
    },
    summary: 'A non-forcing gambit occurrence whose claimed compensation must be resolved by engine evidence.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Halloween_Gambit',
  }),
  trapPilotCandidate({
    id: 'scotch-nh6-sacrifice-v1',
    title: 'Scotch Nh6 sacrifice candidate',
    aliases: ['Scotch opening trap'],
    familyId: 'scotch-sacrifice-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Scotch Game' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'd2d4', 'e5d4', 'f1c4', 'f8c5', 'f3g5'],
    offer: {
      moveUci: 'f3g5',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White develops the knight to g5 and invites a rim-knight defence of f7.',
    },
    response: {
      id: 'defend-f7-with-nh6',
      movesUci: ['g8h6'],
      explanation: 'Black plays Nh6 and allows a forcing exchange on f7.',
    },
    punishment: {
      lineUci: ['g5f7', 'h6f7', 'c4f7', 'e8f7', 'd1h5', 'g7g6', 'h5c5'],
      outcome: 'MATERIAL',
      explanation: 'Nxf7, Nxf7, Bxf7+, Kxf7, Qh5+, g6 and Qxc5 recover the sacrificed material and win the bishop.',
    },
    safeDefense: {
      moveUci: 'd7d5',
      explanation: 'd5 challenges the centre before committing the knight to h6.',
    },
    summary: 'A Scotch-family sacrifice that converts king displacement into material recovery.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Scotch_Game',
  }),
  trapPilotCandidate({
    id: 'fishing-pole-italian-route-v1',
    title: 'Fishing Pole Italian route candidate',
    aliases: ['Fishing Pole, Italian route'],
    familyId: 'fishing-pole-family',
    side: 'BLACK',
    soundness: 'UNASSESSED',
    opening: { name: 'Italian Game' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'f1c4', 'g8f6', 'd2d3', 'f6g4', 'h2h3', 'h7h5'],
    offer: {
      moveUci: 'h7h5',
      role: 'SACRIFICE',
      explanation: 'Black offers the g4 knight after inducing h3 in an Italian move order.',
    },
    response: {
      id: 'h-pawn-captures-knight',
      movesUci: ['h3g4'],
      explanation: 'White takes the knight and opens the h-file structure.',
    },
    punishment: {
      lineUci: ['h5g4'],
      outcome: 'POSITIONAL_BIND',
      explanation: 'hxg4 opens the h-file and creates the attacking structure; deeper claims remain evidence-dependent.',
    },
    safeDefense: {
      moveUci: 'c2c3',
      explanation: 'c3 declines the knight and supports a central expansion.',
    },
    summary: 'A distinct Fishing Pole family occurrence used to compare move-order and population effects.',
    discoveryRef: 'https://en.wikipedia.org/wiki/List_of_chess_traps',
  }),
  trapPilotCandidate({
    id: 'scotch-center-fork-nxe5-v1',
    title: 'Scotch centre-fork candidate',
    aliases: ['Scotch centre trap'],
    familyId: 'scotch-center-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Scotch Game' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'd2d4', 'e5d4', 'f1c4', 'f8c5', 'e1g1'],
    offer: {
      moveUci: 'e1g1',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White castles and leaves the central e5 pawn apparently available to the c6 knight.',
    },
    response: {
      id: 'knight-captures-e5',
      movesUci: ['c6e5'],
      explanation: 'Black takes e5 before completing development.',
    },
    punishment: {
      lineUci: ['f3e5', 'd7d5', 'f1e1', 'g8e7', 'd1d4'],
      outcome: 'MATERIAL',
      explanation: 'Nxe5, d5, Re1, Ne7 and Qxd4 exploit the pinned and overloaded centre.',
    },
    safeDefense: {
      moveUci: 'd7d6',
      explanation: 'd6 reinforces e5 and completes the central structure.',
    },
    summary: 'A development-lead occurrence in which early central grabbing exposes tactical pins.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Scotch_Game',
  }),
  trapPilotCandidate({
    id: 'najdorf-poisoned-pawn-rb1-v1',
    title: 'Najdorf poisoned-pawn candidate',
    aliases: ['Poisoned Pawn Variation'],
    familyId: 'najdorf-poisoned-pawn-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Sicilian Defence, Najdorf Poisoned Pawn' },
    setupMoves: ['e2e4', 'c7c5', 'g1f3', 'd7d6', 'd2d4', 'c5d4', 'f3d4', 'g8f6', 'b1c3', 'a7a6', 'c1g5', 'e7e6', 'f2f4', 'd8b6', 'd1d2'],
    offer: {
      moveUci: 'd1d2',
      role: 'SACRIFICE',
      explanation: 'White leaves b2 available while completing the standard Qd2 attacking setup.',
    },
    response: {
      id: 'queen-captures-b2',
      movesUci: ['b6b2'],
      explanation: 'Black accepts the b2 pawn and moves the queen away from the king.',
    },
    punishment: {
      lineUci: ['a1b1', 'b2a3', 'e4e5'],
      outcome: 'POSITIONAL_BIND',
      explanation: 'Rb1, Qa3 and e5 gain tempi against the queen and open the centre.',
    },
    safeDefense: {
      moveUci: 'f8e7',
      explanation: 'Be7 develops and declines the pawn.',
    },
    summary: 'A high-complexity poisoned-pawn occurrence retained as DRAFT until engine and population evidence resolve the compensation.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Poisoned_Pawn_Variation',
  }),
  trapPilotCandidate({
    id: 'scandinavian-queen-trap-nc7-v1',
    title: 'Scandinavian queen-trap mate candidate',
    aliases: ['Scandinavian Queen Trap'],
    familyId: 'scandinavian-queen-trap-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Scandinavian Defence' },
    setupMoves: ['e2e4', 'd7d5', 'e4d5', 'd8d5', 'b1c3', 'd5a5', 'd2d4', 'g8f6', 'g1f3', 'c8g4', 'h2h3', 'g4h5', 'g2g4'],
    offer: {
      moveUci: 'g2g4',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White pushes g4 and permits the f6 knight to capture with apparent tactical gain.',
    },
    response: {
      id: 'knight-captures-g4',
      movesUci: ['f6g4'],
      explanation: 'Black accepts the pawn and enters a sequence where the queen becomes overextended.',
    },
    punishment: {
      lineUci: ['h3g4', 'h5g4', 'b2b4', 'a5b4', 'c1d2', 'b4d4', 'f3d4', 'g4d1', 'd4b5', 'd1c2', 'b5c7'],
      outcome: 'MATE',
      explanation: 'The forcing pawn, queen and bishop exchanges end with Nxc7 mate.',
    },
    safeDefense: {
      moveUci: 'h5g6',
      explanation: 'Bg6 retreats the bishop and avoids the forcing capture sequence.',
    },
    summary: 'A long promotion-free legality stress case ending in a knight mate on c7.',
    discoveryRef: 'https://chesstrapguide.com/trap/scandinavian-trap/',
  }),
  trapPilotCandidate({
    id: 'danish-bird-poisoned-g2-v1',
    title: 'Danish Bird poisoned-g2 candidate',
    aliases: ['Danish Bird Trap'],
    familyId: 'danish-bird-family',
    side: 'WHITE',
    soundness: 'UNASSESSED',
    opening: { name: 'Danish Gambit Accepted' },
    setupMoves: ['e2e4', 'e7e5', 'd2d4', 'e5d4', 'c2c3', 'd4c3', 'f1c4', 'c3b2', 'c1b2', 'd8g5', 'g1f3'],
    offer: {
      moveUci: 'g1f3',
      role: 'SACRIFICE',
      explanation: 'White develops Nf3 and deliberately leaves g2 available to the black queen.',
    },
    response: {
      id: 'queen-captures-g2',
      movesUci: ['g5g2'],
      explanation: 'Black takes the poisoned g2 pawn and allows the rook and bishops to gain forcing tempi.',
    },
    punishment: {
      lineUci: ['h1g1', 'g2h3', 'c4f7', 'e8f7', 'f3g5', 'f7e8', 'g5h3'],
      outcome: 'MATERIAL',
      explanation: 'Rg1, Qh3, Bxf7+, Kxf7, Ng5+ and Nxh3 trap and win the queen.',
    },
    safeDefense: {
      moveUci: 'd7d6',
      explanation: 'd6 develops and declines the g2 pawn.',
    },
    summary: 'A Danish Gambit occurrence built around a deliberately poisoned kingside pawn.',
    discoveryRef: 'https://www.thechesswebsite.com/danish-bird-trap/',
  }),
] as const;
