import { trapPilotCandidate } from './trap-pilot.candidate-builder';

export const TRAP_PILOT_CLASSIC_CANDIDATES = [
  trapPilotCandidate({
    id: 'damiano-nxe5-v1',
    title: 'Damiano Defence king-exposure candidate',
    aliases: ['Damiano Defence trap'],
    familyId: 'damiano-defence-trap-family',
    side: 'WHITE',
    soundness: 'SOUND',
    opening: { eco: 'C40', name: 'Damiano Defence' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'f7f6', 'f3e5'],
    offer: {
      moveUci: 'f3e5',
      role: 'SACRIFICE',
      explanation: 'White offers the knight to expose the black king and queen.',
    },
    response: {
      id: 'f-pawn-captures-knight',
      movesUci: ['f6e5'],
      explanation: 'Black accepts the knight and opens the king to Qh5 check.',
    },
    punishment: {
      lineUci: ['d1h5', 'e8e7', 'h5e5'],
      outcome: 'MATERIAL',
      explanation: 'White checks, displaces the king, and recovers the pawn while attacking the rook and king.',
    },
    safeDefense: {
      moveUci: 'd8e7',
      explanation: 'Black declines the knight and defends the e5 pawn with the queen.',
    },
    summary: 'A king-exposure candidate with a sound tactical sacrifice against a weakened f-pawn.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Damiano_Defence',
  }),
  trapPilotCandidate({
    id: 'elephant-trap-main-v1',
    title: 'Elephant Trap candidate',
    aliases: ['Elephant Trap'],
    familyId: 'elephant-trap-family',
    side: 'BLACK',
    soundness: 'SOUND',
    opening: { eco: 'D50', name: "Queen's Gambit Declined" },
    setupMoves: ['d2d4', 'd7d5', 'c2c4', 'e7e6', 'b1c3', 'g8f6', 'c1g5', 'b8d7', 'c4d5', 'e6d5'],
    offer: {
      moveUci: 'e6d5',
      role: 'BAIT',
      explanation: 'Black appears to leave d5 available because the f6 knight is pinned.',
    },
    response: {
      id: 'take-d5-pawn',
      movesUci: ['c3d5'],
      explanation: 'White takes the pawn, assuming the pinned knight cannot recapture.',
    },
    punishment: {
      lineUci: ['f6d5', 'g5d8', 'f8b4', 'd1d2', 'b4d2', 'e1d2', 'e8d8'],
      outcome: 'MATERIAL',
      explanation: 'Black uses the intermediate bishop check to recover the queen and emerge a piece ahead.',
    },
    safeDefense: {
      moveUci: 'g1f3',
      explanation: 'White develops instead of trying to exploit the apparent pin tactically.',
    },
    summary: 'A classic pin-deflection candidate with a forcing intermediate check.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Queen%27s_Gambit_Declined%2C_Elephant_Trap',
  }),
  trapPilotCandidate({
    id: 'lasker-underpromotion-v1',
    title: 'Lasker Trap underpromotion candidate',
    aliases: ['Lasker Trap'],
    familyId: 'lasker-trap-family',
    side: 'BLACK',
    soundness: 'PLAYABLE_RISK',
    opening: { eco: 'D08', name: 'Albin Countergambit' },
    setupMoves: ['d2d4', 'd7d5', 'c2c4', 'e7e5', 'd4e5', 'd5d4', 'e2e3', 'f8b4', 'c1d2', 'd4e3'],
    offer: {
      moveUci: 'd4e3',
      role: 'BAIT',
      explanation: 'Black advances the passed pawn and offers the b4 bishop.',
    },
    response: {
      id: 'bishop-captures-b4',
      movesUci: ['d2b4'],
      explanation: 'White takes the bishop and overlooks the promotion tactic.',
    },
    punishment: {
      lineUci: ['e3f2', 'e1e2', 'f2g1n'],
      outcome: 'MATERIAL',
      explanation: 'The pawn promotes to a knight with check, preserving the tactical bind and material gain.',
    },
    safeDefense: {
      moveUci: 'f2e3',
      explanation: 'White accepts doubled pawns and removes the dangerous passer.',
    },
    summary: 'An underpromotion candidate that requires promotion-aware UCI replay.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Albin_Countergambit%2C_Lasker_Trap',
  }),
  trapPilotCandidate({
    id: 'mortimer-qa5-fork-v1',
    title: 'Mortimer Trap fork candidate',
    aliases: ['Mortimer Trap'],
    familyId: 'mortimer-trap-family',
    side: 'BLACK',
    soundness: 'DUBIOUS',
    opening: { eco: 'C65', name: 'Ruy Lopez, Berlin Defence' },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'b8c6', 'f1b5', 'g8f6', 'd2d3', 'c6e7'],
    offer: {
      moveUci: 'c6e7',
      role: 'BAIT',
      explanation: 'Black retreats the knight and appears to leave e5 undefended.',
    },
    response: {
      id: 'take-e5-pawn',
      movesUci: ['f3e5'],
      explanation: 'White takes the pawn and exposes the bishop and knight to a queen fork.',
    },
    punishment: {
      lineUci: ['c7c6', 'b5a4', 'd8a5'],
      outcome: 'MATERIAL',
      explanation: 'Black attacks the bishop and then forks the king and e5 knight with Qa5.',
    },
    safeDefense: {
      moveUci: 'b5c4',
      explanation: 'White develops the bishop actively instead of taking the pawn.',
    },
    summary: 'A deliberately inferior setup candidate used to test prominent objective-risk warnings.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Ruy_Lopez%2C_Mortimer_Trap',
  }),
  trapPilotCandidate({
    id: 'marshall-petrov-bxh2-v1',
    title: 'Marshall Trap Petrov candidate',
    aliases: ['Marshall Trap'],
    familyId: 'marshall-petrov-trap-family',
    side: 'BLACK',
    soundness: 'SOUND',
    opening: { eco: 'C42', name: "Petrov's Defence" },
    setupMoves: ['e2e4', 'e7e5', 'g1f3', 'g8f6', 'f3e5', 'd7d6', 'e5f3', 'f6e4', 'd2d4', 'd6d5', 'f1d3', 'f8d6', 'e1g1', 'e8g8', 'c2c4', 'c8g4', 'c4d5', 'f7f5'],
    offer: {
      moveUci: 'f7f5',
      role: 'TACTICAL_PERMISSION',
      explanation: 'Black builds pressure on h2 and invites the rook to the e-file.',
    },
    response: {
      id: 'rook-to-e1',
      movesUci: ['f1e1'],
      explanation: 'White centralizes the rook but permits the bishop sacrifice and knight fork.',
    },
    punishment: {
      lineUci: ['d6h2', 'g1h2', 'e4f2'],
      outcome: 'MATERIAL',
      explanation: 'The bishop sacrifice drags the king to h2 and the knight forks major pieces from f2.',
    },
    safeDefense: {
      moveUci: 'b1c3',
      explanation: 'White develops the knight and reinforces the centre instead of entering the tactic.',
    },
    summary: 'A deflection-and-fork candidate in a mainstream opening structure.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Petrov%27s_Defence%2C_Marshall_Trap',
  }),
  trapPilotCandidate({
    id: 'rubinstein-f5-v1',
    title: 'Rubinstein Trap candidate',
    aliases: ['Rubinstein Trap'],
    familyId: 'rubinstein-trap-family',
    side: 'WHITE',
    soundness: 'SOUND',
    opening: { eco: 'D60', name: "Queen's Gambit Declined, Orthodox Defence" },
    setupMoves: ['d2d4', 'd7d5', 'g1f3', 'g8f6', 'c2c4', 'e7e6', 'c1g5', 'b8d7', 'e2e3', 'f8e7', 'b1c3', 'e8g8', 'a1c1', 'f8e8', 'd1c2', 'a7a6', 'c4d5', 'e6d5', 'f1d3', 'c7c6', 'e1g1', 'f6e4', 'g5f4'],
    offer: {
      moveUci: 'g5f4',
      role: 'TACTICAL_PERMISSION',
      explanation: 'White completes development while leaving a tactical pressure point on d5 and c7.',
    },
    response: {
      id: 'advance-f-pawn',
      movesUci: ['f7f5'],
      explanation: 'Black supports the e4 knight but loosens the tactical defence of d5.',
    },
    punishment: {
      lineUci: ['c3d5'],
      outcome: 'MATERIAL',
      explanation: 'White wins the d5 pawn; cxd5 would allow Bc7 and trap the queen.',
    },
    safeDefense: {
      moveUci: 'd7f8',
      explanation: 'Black reorganizes without weakening the d5 tactical structure.',
    },
    summary: 'A positional-looking candidate where the punishment is a pawn win backed by a queen-trap threat.',
    discoveryRef: 'https://en.wikipedia.org/wiki/Queen%27s_Gambit_Declined%2C_Rubinstein_Trap',
  }),
] as const;
