export const TRAINING_STATS_RECENT_ATTEMPTS = 5;
export const WEAK_SUBLINE_PERCENTAGE = 0.3;

export const TRAINING_MODE_LINE = 'LINE';
export const TRAINING_MODE_MARATHON = 'MARATHON';
export const TRAINING_MODE_WEAK_SUBLINES = 'WEAK_SUBLINES';
export const TRAINING_MODE_UNTRAINED_SUBLINES = 'UNTRAINED_SUBLINES';
export const TRAINING_MODE_MIXED_WEAK_UNTRAINED = 'MIXED_WEAK_UNTRAINED';

export const SCORED_TRAINING_RESULTS = ['PASSED', 'FAILED'] as const;
