import type { OpeningClassificationRule } from './openingClassification.types';

/**
 * Coverage-expansion rules for generated opening-book families that were not
 * covered by the RB-003 foundation. Broad family defaults come first, followed
 * by narrow exceptions where the family default would misrepresent the choice.
 */
export const OPENING_CLASSIFICATION_COVERAGE_RULES: readonly OpeningClassificationRule[] = [
  {
    id: 'family-zukertort-opening',
    namePattern: /^Zukertort Opening(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['BALANCED', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: '1.Nf3 is a sound flexible first move whose named branches frequently transpose into established flank and queen-pawn structures.',
  },
  {
    id: 'family-pterodactyl-defense',
    namePattern: /^Pterodactyl Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SHARP', 'SURPRISE'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'Pterodactyl setups are playable Modern/Sicilian hybrids that concede central space in exchange for dynamic counterplay.',
  },
  {
    id: 'family-indian-defense-generic',
    namePattern: /^Indian Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'The generic Indian move order beginning with ...Nf6 is objectively sound and usually transposes into established Indian systems.',
  },
  {
    id: 'family-nimzowitsch-defense',
    namePattern: /^Nimzowitsch Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SURPRISE'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: '1...Nc6 is a playable but uncommon response to 1.e4 that invites independent and transpositional play.',
  },
  {
    id: 'family-kings-pawn-game',
    namePattern: /^King's Pawn Game(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['BALANCED', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['BALANCED', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'The broad King’s Pawn Game family represents sound open-game development before a more specific named system is reached.',
  },
  {
    id: 'family-ponziani-opening',
    namePattern: /^Ponziani Opening(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The Ponziani is a respectable open-game sideline that is playable for White but less critical than the principal Italian and Spanish systems.',
  },
  {
    id: 'family-tarrasch-defense',
    namePattern: /^Tarrasch Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['DYNAMIC', 'POSITIONAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Tarrasch is a sound established Queen’s Gambit defence based on active piece play and acceptance of an isolated queen pawn.',
  },
  {
    id: 'family-rat-defense',
    namePattern: /^Rat Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'LOW' },
    black: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SURPRISE'], theoreticalStatus: 'SURPRISE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'LOW' },
    rationale: 'Rat Defence names cover several offbeat but generally playable move orders; low confidence preserves the family’s internal diversity.',
  },
  {
    id: 'family-richter-veresov-attack',
    namePattern: /^Richter-Veresov Attack(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The Veresov is a playable attacking sideline that develops quickly but is less theoretically critical than principal queen-pawn systems.',
  },
  {
    id: 'family-rubinstein-opening',
    namePattern: /^Rubinstein Opening(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SOLID', 'POSITIONAL'], theoreticalStatus: 'SIDELINE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['SOLID', 'POSITIONAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'Rubinstein Opening setups are sound and restrained, emphasizing development and structure over immediate forcing play.',
  },
  {
    id: 'family-lion-defense',
    namePattern: /^Lion Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['SOLID', 'DYNAMIC'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'The Lion is a playable Philidor-style setup that is solid but can become cramped or tactically sharp.',
  },
  {
    id: 'family-neo-grunfeld-defense',
    namePattern: /^Neo-Grünfeld Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['DYNAMIC', 'POSITIONAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Neo-Grünfeld is a principal sound response to fianchetto systems with substantial strategic and theoretical depth.',
  },
  {
    id: 'family-rapport-jobava-system',
    namePattern: /^Rapport-Jobava System(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SHARP', 'SURPRISE'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'The Rapport-Jobava is a playable aggressive system that prioritizes unusual piece placement and practical attacking chances.',
  },
  {
    id: 'family-blumenfeld-countergambit',
    namePattern: /^Blumenfeld Countergambit(?: Accepted)?(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'SIDELINE', theoryBurden: 'HIGH', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Blumenfeld is a respected but risk-bearing Black countergambit that seeks central activity and long-term initiative.',
  },
  {
    id: 'family-kings-knight-opening',
    namePattern: /^King's Knight Opening(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['BALANCED', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'Developing the king knight after 1.e4 is sound and normally transposes into established open-game systems.',
  },
  {
    id: 'family-mikenas-defense',
    namePattern: /^Mikenas Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SURPRISE'], theoreticalStatus: 'SIDELINE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'The Mikenas Defence is an uncommon but playable knight-development response that aims for flexible counterplay.',
  },
  {
    id: 'family-owens-defense',
    namePattern: /^Owen(?:'s)? Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['POSITIONAL', 'SURPRISE'], theoreticalStatus: 'SIDELINE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'Owen’s Defence is playable but less direct than principal responses, using an early queenside fianchetto to challenge the centre.',
  },
  {
    id: 'family-english-defense',
    namePattern: /^English Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'POSITIONAL'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'The English Defence is a playable hypermodern response to queen-pawn openings that seeks imbalance with ...b6 and ...Bb7.',
  },
  {
    id: 'family-amazon-attack',
    namePattern: /^Amazon Attack(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['SURPRISE', 'DYNAMIC'], theoreticalStatus: 'SURPRISE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'LOW' },
    black: { soundness: 'SOUND', character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'LOW' },
    rationale: 'The Amazon Attack is an offbeat queen-development system that is playable as a surprise but not a principal opening choice.',
  },
  {
    id: 'family-formation-attacks',
    namePattern: /^(?:Formation:|Creepy Crawly Formation)(?:\b|:|,)/i,
    white: { character: ['SURPRISE'], theoreticalStatus: 'SURPRISE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'LOW' },
    black: { character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'LOW' },
    rationale: 'These formation labels describe unusual setups too diverse for a reliable objective soundness judgment, so only low-confidence structural traits are assigned.',
  },
  {
    id: 'family-goldsmith-defense',
    namePattern: /^Goldsmith Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'LOW' },
    black: { soundness: 'DUBIOUS', character: ['SURPRISE'], theoreticalStatus: 'SURPRISE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'LOW' },
    rationale: 'The Goldsmith Defence spends time on a flank pawn without sufficient central justification and is primarily a surprise choice.',
  },
  {
    id: 'family-kangaroo-defense',
    namePattern: /^Kangaroo Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SURPRISE'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'The Kangaroo is a playable offbeat defence related to English and Nimzo-Indian structures, with flexible but non-principal move orders.',
  },
  {
    id: 'family-kings-pawn-opening',
    namePattern: /^King's Pawn Opening(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['BALANCED', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'The generic King’s Pawn Opening label represents a sound central first move before a more specific family is identified.',
  },
  {
    id: 'family-marienbad-system',
    namePattern: /^Marienbad System(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['POSITIONAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'The Marienbad is a sound positional system whose identity is structural rather than tactically forcing.',
  },
  {
    id: 'family-ware-defense',
    namePattern: /^Ware Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'DUBIOUS', character: ['SURPRISE'], theoreticalStatus: 'SURPRISE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'The Ware Defence loses time with a flank pawn and does not contest the centre sufficiently.',
  },
  {
    id: 'family-zukertort-defense',
    namePattern: /^Zukertort Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'LOW' },
    black: { soundness: 'PLAYABLE', character: ['POSITIONAL', 'SURPRISE'], theoreticalStatus: 'SIDELINE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'LOW' },
    rationale: 'Zukertort Defence labels cover uncommon but generally playable setups; low confidence reflects their small and varied sample.',
  },
  {
    id: 'family-english-orangutan',
    namePattern: /^English Orangutan(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SURPRISE'], theoreticalStatus: 'SURPRISE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'LOW' },
    black: { soundness: 'SOUND', character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'LOW' },
    rationale: 'The English Orangutan is an unusual but playable flank-opening hybrid intended primarily as a surprise weapon.',
  },
  {
    id: 'family-hippopotamus-defense',
    namePattern: /^Hippopotamus Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['SOLID', 'DYNAMIC', 'SURPRISE'], theoreticalStatus: 'SIDELINE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'The Hippopotamus is a playable compact setup that concedes space while retaining flexible pawn breaks.',
  },
  {
    id: 'family-pseudo-queens-indian-defense',
    namePattern: /^Pseudo Queen's Indian Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['POSITIONAL'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'The Pseudo Queen’s Indian is a playable positional setup that resembles Queen’s Indian structures without following the principal move order.',
  },
  {
    id: 'family-rare-white-opening-systems',
    namePattern: /^(?:Amsterdam Attack|Anderssen's Opening|Canard Opening|Clemenz Opening|Dresden Opening|Global Opening|Lasker Simul Special|Paleface Attack|Portuguese Opening|Queen's Pawn(?:\b|:|,)|Valencia Opening|Yusupov-Rubinstein System)(?:\b|:|,)/i,
    white: { character: ['SURPRISE'], theoreticalStatus: 'SURPRISE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'LOW' },
    black: { character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'LOW' },
    rationale: 'These rare White systems are grouped only for low-confidence surprise and role traits; objective soundness remains explicitly unknown.',
  },
  {
    id: 'family-bongcloud-attack',
    namePattern: /^Bongcloud Attack(?:\b|:|,)/i,
    white: { soundness: 'DUBIOUS', character: ['SURPRISE'], theoreticalStatus: 'SURPRISE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The Bongcloud deliberately loses development time and king safety and is objectively dubious despite its practical novelty value.',
  },
  {
    id: 'family-rare-black-defenses',
    namePattern: /^(?:Australian Defense|Carr Defense|Czech Defense|Döry Defense|East Indian Defense|Gunderam Defense|Horwitz Defense|Mexican Defense|Montevideo Defense|Polish Defense|Queen's Indian Accelerated|Robatsch Defense|Slav Indian|Vulture Defense|Wade Defense|Zaire Defense)(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'LOW' },
    black: { soundness: 'PLAYABLE', character: ['SURPRISE', 'DYNAMIC'], theoreticalStatus: 'SIDELINE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'LOW' },
    rationale: 'These uncommon defences are generally playable but too heterogeneous for higher-confidence family claims; they are grouped as low-theory sidelines.',
  },
  {
    id: 'family-dubious-flank-defenses',
    namePattern: /^(?:Barnes Defense|Borg Defense|Fried Fox Defense|Lemming Defense)(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'DUBIOUS', character: ['SURPRISE'], theoreticalStatus: 'SURPRISE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'These early flank or weakening moves lose central influence or king safety without sufficient compensation.',
  },
  {
    id: 'line-kings-pawn-damiano-defense',
    namePattern: /^King's Pawn Game: Damiano Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'DUBIOUS', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SURPRISE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Damiano weakens Black’s king and permits forcing tactical punishment, overriding the generic King’s Pawn Game default.',
  },
  {
    id: 'line-nimzowitsch-colorado-countergambit',
    namePattern: /^Nimzowitsch Defense: Colorado Countergambit(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'RISKY', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SURPRISE', theoryBurden: 'MEDIUM', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Colorado Countergambit is a materially and positionally risky Black pawn sacrifice that needs a narrow override.',
  },
  {
    id: 'line-nimzowitsch-colorado-accepted',
    namePattern: /^Nimzowitsch Defense: Colorado Countergambit Accepted(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['GAMBIT_ACCEPTOR', 'RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'RISKY', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SURPRISE', theoryBurden: 'MEDIUM', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    rationale: 'Accepted identifies White as the accepting side while Black remains the risky gambit offerer.',
  },
  {
    id: 'line-ponziani-countergambit',
    namePattern: /^Ponziani Opening: Ponziani Countergambit(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'RISKY', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Ponziani Countergambit is a forcing but risk-bearing Black pawn sacrifice and overrides the broad Ponziani family.',
  },
  {
    id: 'line-blumenfeld-countergambit-accepted',
    namePattern: /^Blumenfeld Countergambit Accepted(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['GAMBIT_ACCEPTOR', 'RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'SIDELINE', theoryBurden: 'HIGH', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    rationale: 'Accepted makes White the accepting side while Black remains the countergambit offerer.',
  },
];
