import type { OpeningClassificationRule } from './openingClassification.types';

/**
 * Rules are applied in declaration order. Broad family defaults come first;
 * lexical modifiers and specific subfamily/line overrides come later.
 */
export const OPENING_CLASSIFICATION_RULES: readonly OpeningClassificationRule[] = [
  {
    id: 'family-english-opening',
    namePattern: /^English Opening(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['BALANCED', 'POSITIONAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['BALANCED', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'The English is a sound flank-opening family with positional and dynamic branches.',
  },
  {
    id: 'family-reti-opening',
    namePattern: /^(?:Réti|Reti) Opening(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL', 'BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['BALANCED', 'POSITIONAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'The Réti is a sound positional family with flexible transpositions.',
  },
  {
    id: 'family-kings-indian-attack',
    namePattern: /^King's Indian Attack(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'The King’s Indian Attack is sound and system-oriented, with attacking potential rather than objective dubiousness.',
  },
  {
    id: 'family-bird-opening',
    namePattern: /^Bird Opening(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'Bird’s Opening is playable but concedes more structural and king-safety risk than principal first moves.',
  },
  {
    id: 'family-nimzo-larsen-attack',
    namePattern: /^Nimzo-Larsen Attack(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'SIDELINE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'The Nimzo-Larsen is a respectable sideline emphasizing flexible piece placement.',
  },
  {
    id: 'family-polish-opening',
    namePattern: /^Polish Opening(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['DYNAMIC'], theoreticalStatus: 'SURPRISE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'The Polish is playable as a surprise weapon but is not a principal first-move family.',
  },
  {
    id: 'family-grob-opening',
    namePattern: /^Grob Opening(?:\b|:|,)/i,
    white: { soundness: 'DUBIOUS', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SURPRISE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The Grob weakens White’s position for insufficient objective compensation, while Black can respond soundly.',
  },
  {
    id: 'family-weak-first-move-openings',
    namePattern: /^(?:Barnes Opening|Ware Opening|Kádas Opening|Sodium Attack|Amar Opening)(?:\b|:|,)/i,
    white: { soundness: 'DUBIOUS', character: ['SURPRISE' as never], theoreticalStatus: 'SURPRISE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'These rare first moves lose central influence or development time and are primarily surprise choices.',
  },
  {
    id: 'family-van-geet-opening',
    namePattern: /^Van Geet Opening(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['DYNAMIC'], theoreticalStatus: 'SIDELINE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: '1.Nc3 is playable but less direct than principal central first moves.',
  },
  {
    id: 'family-quiet-first-move-openings',
    namePattern: /^(?:Mieses Opening|Hungarian Opening|Saragossa Opening|Van't Kruijs Opening)(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['SOLID', 'POSITIONAL'], theoreticalStatus: 'SIDELINE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'These quiet first moves are playable but concede some first-move pressure.',
  },
  {
    id: 'family-queens-pawn-game',
    namePattern: /^Queen's Pawn Game(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL', 'BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['POSITIONAL', 'BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'Queen’s-pawn structures are generally sound and positional.',
  },
  {
    id: 'family-london-system',
    namePattern: /^(?:London System|Queen's Pawn Game: London System)(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SOLID', 'POSITIONAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['BALANCED', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The London is objectively sound and structure-oriented, though Black has active counterplay.',
  },
  {
    id: 'family-colle-system',
    namePattern: /^(?:Colle System|Queen's Pawn Game: Colle System)(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SOLID', 'POSITIONAL'], theoreticalStatus: 'SIDELINE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The Colle is a sound low-theory system, usually less ambitious than principal queen’s-pawn lines.',
  },
  {
    id: 'family-trompowsky-attack',
    namePattern: /^Trompowsky Attack(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'The Trompowsky is a sound independent opening that often creates early imbalance.',
  },
  {
    id: 'family-torre-attack',
    namePattern: /^Torre Attack(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SOLID', 'POSITIONAL'], theoreticalStatus: 'SIDELINE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'The Torre is a sound system opening with modest theory burden.',
  },
  {
    id: 'family-catalan-opening',
    namePattern: /^Catalan Opening(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The Catalan is a principal sound opening with deep positional theory.',
  },
  {
    id: 'family-queens-gambit',
    namePattern: /^Queen's Gambit(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The Queen’s Gambit is a principal sound opening; the word gambit does not imply dubiousness.',
  },
  {
    id: 'family-slav-defense',
    namePattern: /^Slav Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SOLID', 'POSITIONAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Slav is a principal solid defence to the Queen’s Gambit.',
  },
  {
    id: 'family-semi-slav-defense',
    namePattern: /^Semi-Slav Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SOLID', 'SHARP'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Semi-Slav is objectively sound but can lead to extremely sharp principal theory.',
  },
  {
    id: 'family-queens-indian-defense',
    namePattern: /^Queen's Indian Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SOLID', 'POSITIONAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Queen’s Indian is a principal positional defence.',
  },
  {
    id: 'family-nimzo-indian-defense',
    namePattern: /^Nimzo-Indian Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Nimzo-Indian is a principal sound defence with structural and dynamic complexity.',
  },
  {
    id: 'family-kings-indian-defense',
    namePattern: /^King's Indian Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The King’s Indian is objectively sound and deliberately dynamic.',
  },
  {
    id: 'family-grunfeld-defense',
    namePattern: /^(?:Grünfeld|Grunfeld) Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Grünfeld is a principal theoretical defence based on dynamic pressure against the centre.',
  },
  {
    id: 'family-dutch-defense',
    namePattern: /^Dutch Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'The Dutch is playable and ambitious but accepts more king-safety and structural risk than principal defences.',
  },
  {
    id: 'family-benoni-defense',
    namePattern: /^(?:Benoni Defense|Modern Benoni)(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'Benoni structures are playable but strategically risky for Black and usually dynamic for both sides.',
  },
  {
    id: 'family-benko-gambit',
    namePattern: /^Benko Gambit(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Benko is a respectable long-term positional pawn sacrifice by Black, not a generic dubious gambit.',
  },
  {
    id: 'family-budapest-gambit',
    namePattern: /^Budapest Gambit(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Budapest is playable as an active sideline but is less theoretically critical than principal defences.',
  },
  {
    id: 'family-englund-gambit',
    namePattern: /^Englund Gambit(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'DUBIOUS', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SURPRISE', theoryBurden: 'LOW', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Englund gives Black insufficient compensation against accurate play.',
  },
  {
    id: 'family-old-indian-defense',
    namePattern: /^Old Indian Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['SOLID', 'POSITIONAL'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'The Old Indian is playable and solid but more passive than principal Indian defences.',
  },
  {
    id: 'family-bogo-indian-defense',
    namePattern: /^Bogo-Indian Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SOLID', 'POSITIONAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Bogo-Indian is a sound positional defence.',
  },
  {
    id: 'family-sicilian-defense',
    namePattern: /^Sicilian Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Sicilian is a principal sound defence that deliberately creates imbalance.',
  },
  {
    id: 'family-french-defense',
    namePattern: /^French Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SOLID', 'DYNAMIC'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The French is a principal sound defence with characteristic space and pawn-chain tension.',
  },
  {
    id: 'family-caro-kann-defense',
    namePattern: /^Caro-Kann Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SOLID', 'POSITIONAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Caro-Kann is a principal sound defence usually associated with structural solidity.',
  },
  {
    id: 'family-scandinavian-defense',
    namePattern: /^Scandinavian Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['BALANCED', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['BALANCED', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'The Scandinavian is playable but usually yields White comfortable development compared with principal defences.',
  },
  {
    id: 'family-pirc-defense',
    namePattern: /^Pirc Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Pirc is a sound hypermodern defence with dynamic counterplay and theoretical risk.',
  },
  {
    id: 'family-modern-defense',
    namePattern: /^Modern Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'The Modern is playable and flexible but can concede substantial central space.',
  },
  {
    id: 'family-alekhine-defense',
    namePattern: /^Alekhine Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'Alekhine’s Defence is playable and provocative but allows White a large centre.',
  },
  {
    id: 'family-owens-defense',
    namePattern: /^Owen's Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['POSITIONAL'], theoreticalStatus: 'SIDELINE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'Owen’s Defence is playable but less direct and less theoretically critical than principal responses to 1.e4.',
  },
  {
    id: 'family-st-george-defense',
    namePattern: /^St\. George Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'RISKY', character: ['SURPRISE' as never], theoreticalStatus: 'SURPRISE', theoryBurden: 'LOW', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'The St. George is a provocative surprise defence that concedes central space and development time.',
  },
  {
    id: 'family-ruy-lopez',
    namePattern: /^Ruy Lopez(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The Ruy Lopez is a principal sound opening with deep positional and tactical theory.',
  },
  {
    id: 'family-italian-game',
    namePattern: /^Italian Game(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['BALANCED', 'DYNAMIC'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['BALANCED', 'DYNAMIC'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The Italian is a principal sound opening with both quiet and tactical branches.',
  },
  {
    id: 'family-scotch-game',
    namePattern: /^Scotch Game(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The Scotch is a sound central opening that often clarifies the position early.',
  },
  {
    id: 'family-four-knights-game',
    namePattern: /^Four Knights Game(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SOLID', 'BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SOLID', 'BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The Four Knights is a sound classical opening, usually stable unless a sharp subline is selected.',
  },
  {
    id: 'family-vienna-game',
    namePattern: /^Vienna Game(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The Vienna is sound and can become sharply tactical without being inherently dubious.',
  },
  {
    id: 'family-kings-gambit',
    namePattern: /^King's Gambit(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The King’s Gambit is objectively playable but risky for White; Black has sound principal responses.',
  },
  {
    id: 'family-danish-gambit',
    namePattern: /^Danish Gambit(?:\b|:|,)/i,
    white: { soundness: 'RISKY', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The Danish offers substantial material for initiative and is riskier than principal open-game choices.',
  },
  {
    id: 'family-bishops-opening',
    namePattern: /^Bishop's Opening(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['BALANCED', 'DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'The Bishop’s Opening is sound and flexible, often transposing to other open games.',
  },
  {
    id: 'family-center-game',
    namePattern: /^Center Game(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['DYNAMIC'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'The Center Game is playable but usually releases central tension earlier than principal open games.',
  },
  {
    id: 'family-philidor-defense',
    namePattern: /^Philidor Defense(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    black: { soundness: 'PLAYABLE', character: ['SOLID', 'POSITIONAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    rationale: 'The Philidor is playable and solid but can be passive compared with principal 1.e4 e5 defences.',
  },
  {
    id: 'family-petrov-defense',
    namePattern: /^(?:Petrov's Defense|Russian Game)(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SOLID', 'POSITIONAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SOLID', 'POSITIONAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Petroff is a principal sound defence with a solid reputation and substantial theory.',
  },
  {
    id: 'family-latvian-gambit',
    namePattern: /^Latvian Gambit(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'DUBIOUS', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SURPRISE', theoryBurden: 'MEDIUM', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Latvian is an objectively dubious pawn sacrifice by Black despite practical tactical chances.',
  },
  {
    id: 'family-elephant-gambit',
    namePattern: /^Elephant Gambit(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'LOW', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'DUBIOUS', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SURPRISE', theoryBurden: 'LOW', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Elephant Gambit sacrifices central stability for insufficient compensation.',
  },
  {
    id: 'family-three-knights-opening',
    namePattern: /^Three Knights Opening(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['BALANCED'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'The Three Knights is sound but often transitional rather than a final strategic identity.',
  },

  {
    id: 'modifier-named-gambit-is-sharp-not-automatically-dubious',
    namePattern: /\bGambit\b/i,
    white: { character: ['SHARP', 'TACTICAL'] },
    black: { character: ['SHARP', 'TACTICAL'] },
    rationale: 'A named gambit is usually tactically forcing, but the word alone does not determine objective soundness or which side offered material.',
  },
  {
    id: 'modifier-main-line',
    namePattern: /\bMain Line\b/i,
    white: { theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH' },
    black: { theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH' },
    rationale: 'A named main line signals established theory for both sides.',
  },
  {
    id: 'modifier-classical-variation',
    namePattern: /\bClassical (?:Variation|System)\b/i,
    white: { theoreticalStatus: 'MAINLINE' },
    black: { theoreticalStatus: 'MAINLINE' },
    rationale: 'A classical named branch is normally established rather than a pure surprise line.',
  },
  {
    id: 'modifier-exchange-variation',
    namePattern: /\bExchange Variation\b/i,
    white: { character: ['POSITIONAL'] },
    black: { character: ['POSITIONAL'] },
    rationale: 'Exchange variations commonly reduce one source of tension and emphasize structural play, without implying complete solidity.',
  },

  {
    id: 'subfamily-english-mikenas-carls',
    namePattern: /^English Opening:.*(?:Mikenas(?:-Carls)?|Flohr-Mikenas-Carls)/i,
    white: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'Mikenas-Carls structures share an aggressive White setup and dynamic Black counterplay across several generated names.',
  },
  {
    id: 'line-english-mikenas-nei-gambit',
    namePattern: /^English Opening:.*Flohr-Mikenas-Carls Variation, Nei Gambit(?:\b|:|,)/i,
    white: { soundness: 'RISKY', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SURPRISE', theoryBurden: 'MEDIUM', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'MEDIUM' },
    black: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'MEDIUM' },
    rationale: 'The Nei Gambit is a more forcing and materially risky Mikenas branch and therefore overrides the broad English defaults.',
  },
  {
    id: 'subfamily-italian-evans-gambit',
    namePattern: /^Italian Game: Evans Gambit(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'White chooses a playable attacking pawn sacrifice; Black has sound principal ways to meet it.',
  },
  {
    id: 'line-italian-evans-gambit-accepted',
    namePattern: /^Italian Game: Evans Gambit(?:,|:) Accepted|^Italian Game: Evans Gambit Accepted/i,
    white: { soundness: 'PLAYABLE', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['GAMBIT_ACCEPTOR', 'RESPONDER'], confidence: 'HIGH' },
    rationale: 'Accepting the Evans pawn is a principled Black response even though the resulting position is sharp.',
  },
  {
    id: 'line-queens-gambit-accepted',
    namePattern: /^Queen's Gambit Accepted(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['POSITIONAL', 'DYNAMIC'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['GAMBIT_ACCEPTOR', 'RESPONDER'], confidence: 'HIGH' },
    rationale: 'The Queen’s Gambit Accepted is a principal sound Black defence, not evidence that Black plays dubious gambits.',
  },
  {
    id: 'line-queens-gambit-declined',
    namePattern: /^Queen's Gambit Declined(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['POSITIONAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SOLID', 'POSITIONAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['GAMBIT_DECLINER', 'RESPONDER'], confidence: 'HIGH' },
    rationale: 'Declining the Queen’s Gambit is a principal solid Black choice.',
  },
  {
    id: 'line-kings-gambit-accepted',
    namePattern: /^King's Gambit Accepted(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['GAMBIT_ACCEPTOR', 'RESPONDER'], confidence: 'HIGH' },
    rationale: 'Black’s acceptance is principled even though White intentionally entered a risky attacking opening.',
  },
  {
    id: 'line-kings-gambit-declined',
    namePattern: /^King's Gambit Declined(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['GAMBIT_DECLINER', 'RESPONDER'], confidence: 'HIGH' },
    rationale: 'Declining is another sound Black response to White’s risky gambit choice.',
  },
  {
    id: 'line-benko-gambit-accepted',
    namePattern: /^Benko Gambit Accepted(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['GAMBIT_ACCEPTOR', 'RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Benko reverses the usual color assumption: Black offers the pawn and White accepts it.',
  },
  {
    id: 'line-benko-gambit-declined',
    namePattern: /^Benko Gambit Declined(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['GAMBIT_DECLINER', 'RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'PLAYABLE', character: ['DYNAMIC', 'SHARP'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    rationale: 'White declines Black’s positional gambit while Black remains the offering side.',
  },
  {
    id: 'subfamily-sicilian-smith-morra-gambit',
    namePattern: /^Sicilian Defense: Smith-Morra Gambit(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The Smith-Morra is playable and dangerous but objectively less critical than principal Open Sicilian choices.',
  },
  {
    id: 'line-sicilian-smith-morra-accepted',
    namePattern: /^Sicilian Defense: Smith-Morra Gambit Accepted(?:\b|:|,)/i,
    white: { soundness: 'PLAYABLE', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'MEDIUM', roles: ['GAMBIT_ACCEPTOR', 'RESPONDER'], confidence: 'HIGH' },
    rationale: 'Black can accept the Smith-Morra pawn soundly while voluntarily entering complications.',
  },
  {
    id: 'subfamily-sicilian-najdorf',
    namePattern: /^Sicilian Defense: Najdorf Variation(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP', 'TACTICAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP', 'TACTICAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Najdorf is a principal highly theoretical and tactically rich Sicilian.',
  },
  {
    id: 'subfamily-sicilian-dragon',
    namePattern: /^Sicilian Defense: (?:Accelerated )?Dragon Variation(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP', 'TACTICAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['DYNAMIC', 'SHARP', 'TACTICAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'Dragon structures are objectively sound and characteristically sharp rather than dubious.',
  },
  {
    id: 'line-blackmar-diemer-gambit',
    namePattern: /^(?:Blackmar-Diemer Gambit|Queen's Pawn Game: Blackmar-Diemer Gambit)(?:\b|:|,)/i,
    white: { soundness: 'RISKY', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SURPRISE', theoryBurden: 'MEDIUM', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'HIGH' },
    rationale: 'The Blackmar-Diemer gives White practical attacking chances but insufficient objective compensation against accurate defence.',
  },
  {
    id: 'line-albin-countergambit',
    namePattern: /^Queen's Gambit Declined: Albin Countergambit(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'RISKY', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SIDELINE', theoryBurden: 'MEDIUM', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Albin is a risky Black countergambit and should override the solid Queen’s Gambit Declined family default.',
  },
  {
    id: 'line-petrov-stafford-gambit',
    namePattern: /^(?:Petrov's Defense|Russian Game):.*Stafford Gambit(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'MEDIUM', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'DUBIOUS', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SURPRISE', theoryBurden: 'MEDIUM', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Stafford is dangerous practically but objectively dubious for Black against accurate play.',
  },
  {
    id: 'line-ruy-lopez-marshall-attack',
    namePattern: /^Ruy Lopez:.*Marshall Attack(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'PRINCIPAL', theoryBurden: 'HIGH', roles: ['GAMBIT_OFFERER', 'INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Marshall is a sound principal pawn sacrifice by Black, demonstrating that gambit play can be fully orthodox.',
  },
  {
    id: 'line-ruy-lopez-schliemann-jaenisch',
    namePattern: /^Ruy Lopez:.*(?:Schliemann|Jaenisch)(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'PLAYABLE', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SIDELINE', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Schliemann/Jaenisch is a respected but riskier sharp Black sideline.',
  },
  {
    id: 'line-italian-traxler-counterattack',
    namePattern: /^Italian Game:.*Traxler Counterattack(?:\b|:|,)/i,
    white: { soundness: 'SOUND', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'MAINLINE', theoryBurden: 'HIGH', roles: ['RESPONDER'], confidence: 'HIGH' },
    black: { soundness: 'RISKY', character: ['SHARP', 'TACTICAL'], theoreticalStatus: 'SIDELINE', theoryBurden: 'HIGH', roles: ['INITIATOR'], confidence: 'HIGH' },
    rationale: 'The Traxler is a highly forcing Black counterattack with substantial objective and practical risk.',
  },
];
