import type { OpeningKnowledgeCompletionFamily } from './openingKnowledge.completion.shared';

export const OPENING_KNOWLEDGE_COMPLETION_BATCH_4: readonly OpeningKnowledgeCompletionFamily[] = [
  {
    family: "Creepy Crawly Formation",
    fixture: "Creepy Crawly Formation: Classical Defense",
    id: "creepy-crawly-formation",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A deliberately slow flank-pawn formation that delays central occupation, seeking flexibility and unusual piece routes at the cost of space.",
    whiteSummary: "Keep the pawn moves connected to a later central break and complete development before the formation becomes too passive.",
    blackSummary: "Take central space, restrict the opponent's breaks and open lines while the flank-pawn setup is still underdeveloped.",
  },
  {
    family: "Dresden Opening",
    fixture: "Dresden Opening: The Goblin",
    id: "dresden-opening",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare offbeat opening that departs from mainstream central development early, aiming mainly for surprise and flexible transposition.",
    whiteSummary: "Use the unusual move only as a move-order device, then establish a sound centre and normal development quickly.",
    blackSummary: "Take central space and develop actively, testing whether the unusual first moves have created a concrete weakness or loss of time.",
  },
  {
    family: "Global Opening",
    fixture: "Global Opening",
    id: "global-opening",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare offbeat opening family whose main practical value is move-order surprise rather than a forcing central claim.",
    whiteSummary: "Convert the surprise into a coherent centre and piece development; avoid additional eccentric moves that compound lost time.",
    blackSummary: "Use principled central development and force the opening to demonstrate a concrete benefit before reacting tactically.",
  },
  {
    family: "Lasker Simul Special",
    fixture: "Lasker Simul Special",
    id: "lasker-simul-special",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare historical sideline built for surprise and practical imbalance rather than mainstream theoretical pressure.",
    whiteSummary: "Keep the unusual move order connected to rapid development and central control, and transpose to sound structures when possible.",
    blackSummary: "Claim the centre and develop efficiently, avoiding unnecessary tactical adventures against a setup that may simply be waiting for overreaction.",
  },
  {
    family: "Paleface Attack",
    fixture: "Paleface Attack",
    id: "paleface-attack",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare attacking sideline that uses an unconventional early deployment to create practical threats and sidestep common theory.",
    whiteSummary: "Make the attacking idea concrete through development and central support rather than launching unsupported pawn or queen moves.",
    blackSummary: "Contest the centre, finish development and neutralize the attack by removing its active pieces rather than chasing superficial threats.",
  },
  {
    family: "Queen's Pawn",
    fixture: "Queen's Pawn, Mengarini Attack",
    id: "queen-s-pawn",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A minimal queen-pawn opening identity centered on an early d4 claim before a more specific system or defense has been determined.",
    whiteSummary: "Support d4, develop the kingside and choose c4 or e4 according to Black's structure.",
    blackSummary: "Challenge d4 with a coherent ...d5, ...Nf6, ...c5 or ...f5 setup and avoid granting White unrestricted central space.",
  },
  {
    family: "Valencia Opening",
    fixture: "Valencia Opening",
    id: "valencia-opening",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare offbeat opening that seeks a nonstandard move order and flexible development rather than an immediate theoretical confrontation.",
    whiteSummary: "Use the move-order surprise to reach a sound centre quickly, keeping the pieces coordinated and king safe.",
    blackSummary: "Occupy the centre and develop naturally, making the unusual setup prove its strategic value before committing to pawn-chasing.",
  },
  {
    family: "Yusupov-Rubinstein System",
    fixture: "Yusupov-Rubinstein System",
    id: "yusupov-rubinstein-system",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A restrained queen-pawn system emphasizing harmonious development, central solidity and flexible transpositions over forcing early play.",
    whiteSummary: "Improve pieces behind the solid centre and prepare c4 or e4 when it creates a real space or structural gain.",
    blackSummary: "Challenge the compact setup before it becomes effortless, using ...c5 or ...e5 and active piece placement to equalize space.",
  },
  {
    family: "Australian Defense",
    fixture: "Australian Defense",
    id: "australian-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare offbeat defense that uses an unusual early move to seek surprise while conceding some central influence.",
    whiteSummary: "Take central space and develop quickly, treating the unusual defense as a tempo opportunity rather than hunting for an immediate refutation.",
    blackSummary: "Connect the unusual move to a concrete central or flank counter and complete development before White's space becomes entrenched.",
  },
  {
    family: "Czech Defense",
    fixture: "Czech Defense",
    id: "czech-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A compact defense related to Pirc/Modern structures, using a restrained pawn setup to control central breaks and prepare counterplay.",
    whiteSummary: "Use the space advantage to complete development and open the centre before Black's compact structure reorganizes.",
    blackSummary: "Keep the pawn shell flexible, challenge White's centre with ...e5 or ...c5 and avoid a passive setup with no freeing break.",
  },
  {
    family: "Döry Defense",
    fixture: "Döry Defense",
    id: "d-ry-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "An uncommon queen-pawn defense that uses a nonstandard piece or pawn order to create asymmetry while retaining central counterplay.",
    whiteSummary: "Build a stable centre and develop normally, asking the unusual setup to prove value before taking tactical risks.",
    blackSummary: "Use the move-order surprise to attack the centre promptly and transpose into a sound structure when the opportunity appears.",
  },
  {
    family: "East Indian Defense",
    fixture: "East Indian Defense",
    id: "east-indian-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A King's Indian-style setup reached against quieter queen-pawn move orders, typically using ...Nf6 and ...g6 while White has not committed to the main c4 structures.",
    whiteSummary: "Use the flexible move order to claim central space and restrict ...e5 or ...c5 breaks before Black completes the fianchetto plan.",
    blackSummary: "Fianchetto, pressure the centre and choose ...d6/...e5 or ...c5 according to White's exact pawn setup.",
  },
  {
    family: "Gunderam Defense",
    fixture: "Gunderam Defense",
    id: "gunderam-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare open-game defense using an unusual early move to defend or counterattack the centre, usually at the cost of natural development.",
    whiteSummary: "Develop with tempo, occupy the centre and avoid premature tactics unless the unusual piece placement creates a concrete target.",
    blackSummary: "Use the unusual setup to generate immediate central pressure, then catch up in development before White can exploit the lost time.",
  },
  {
    family: "Montevideo Defense",
    fixture: "Montevideo Defense",
    id: "montevideo-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare queen-pawn defense that uses an unconventional move order to create asymmetry and flexible central counterplay.",
    whiteSummary: "Take central space and develop efficiently, keeping the centre stable against later breaks.",
    blackSummary: "Challenge the centre promptly and use the unusual move order to transpose into an active structure rather than remaining passive.",
  },
  {
    family: "Queen's Indian Accelerated",
    fixture: "Queen's Indian Accelerated",
    id: "queen-s-indian-accelerated",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A fast Queen's Indian-style setup where Black commits to ...b6/...Bb7 ideas early to pressure e4 and the long diagonal.",
    whiteSummary: "Use the move order to claim central space if Black has delayed another key move, while limiting the b7 bishop.",
    blackSummary: "Make the early fianchetto active through pressure on e4 and timely ...c5 or ...d5 breaks.",
  },
  {
    family: "Robatsch Defense",
    fixture: "Robatsch Defense",
    id: "robatsch-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A Modern Defense family where Black fianchettos and allows White central space, planning to undermine the centre later with pawn breaks and piece pressure.",
    whiteSummary: "Use the broad centre to restrict Black while keeping it tactically sound against ...c5 and ...e5.",
    blackSummary: "Complete the fianchetto and attack White's centre before it becomes stable, choosing the break that best fits White's setup.",
  },
  {
    family: "Vulture Defense",
    fixture: "Vulture Defense",
    id: "vulture-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare dynamic queen-pawn defense using unusual knight placement and Benoni-style pressure to create tactical counterplay against White's centre.",
    whiteSummary: "Keep the centre well supported, question the oddly placed knight and avoid opening lines that improve Black's activity for free.",
    blackSummary: "Use the knight activity and pawn breaks to provoke weaknesses quickly; the setup depends on concrete pressure more than static structure.",
  },
  {
    family: "Wade Defense",
    fixture: "Wade Defense",
    id: "wade-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "An offbeat queen-pawn defense often involving an active early bishop deployment to pressure the centre before Black fixes the pawn structure.",
    whiteSummary: "Build the centre while gaining tempi on the exposed bishop only when it improves development.",
    blackSummary: "Use the active bishop to provoke concessions and follow with a central break; avoid moving the bishop repeatedly without gaining something concrete.",
  },
  {
    family: "Zaire Defense",
    fixture: "Zaire Defense",
    id: "zaire-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare hypermodern defense that concedes central space and seeks counterplay through flexible piece development and later pawn breaks.",
    whiteSummary: "Occupy the centre, complete development and keep the pawn mass supported against delayed counterattacks.",
    blackSummary: "Attack the centre with pieces and a timely pawn break, avoiding passive waiting that leaves White with a free space advantage.",
  },
  {
    family: "Barnes Defense",
    fixture: "Barnes Defense",
    id: "barnes-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A provocative 1...f6-style defense that supports ...e5 but seriously weakens Black's king and delays natural kingside development.",
    whiteSummary: "Open the centre rapidly and develop toward the weakened king, especially before Black can repair the dark-square weaknesses.",
    blackSummary: "If using the setup, establish the central pawn mass quickly and prioritize king safety; further pawn moves usually magnify the opening's risks.",
  },
  {
    family: "Blumenfeld Countergambit Accepted",
    fixture: "Blumenfeld Countergambit Accepted",
    id: "blumenfeld-countergambit-accepted",
    kind: "FULL",
    confidence: "LOW",
    orientation: "The accepted Blumenfeld structure gives White extra queenside material while Black receives a mobile centre, open lines and development-based compensation.",
    whiteSummary: "Blockade the central pawns, finish development and return material if needed to reduce Black's activity.",
    blackSummary: "Use the central majority and open files energetically before White consolidates the extra pawn and closes the position.",
  },
  {
    family: "Bongcloud Attack",
    fixture: "Bongcloud Attack",
    id: "bongcloud-attack",
    kind: "FULL",
    confidence: "LOW",
    orientation: "An intentionally unorthodox opening with an early king move, surrendering castling rights and exposing the king in exchange for surprise value rather than objective opening pressure.",
    whiteSummary: "Keep the centre closed, develop rapidly around the exposed king and avoid further tempi that make king safety worse.",
    blackSummary: "Open the centre and develop with tempo against the displaced king, while avoiding reckless sacrifices when simple activity is sufficient.",
  },
  {
    family: "Center Game Accepted",
    fixture: "Center Game Accepted",
    id: "center-game-accepted",
    kind: "FULL",
    confidence: "LOW",
    orientation: "An accepted Center Game structure where the early d-pawn exchange opens central lines and White seeks rapid development around an exposed queen or recapture.",
    whiteSummary: "Use the open lines to develop quickly and keep the queen active without allowing repeated tempi against it.",
    blackSummary: "Develop with tempo, contest e4 and d4 and simplify if doing so removes White's initiative without conceding structure.",
  },
  {
    family: "Danish Gambit",
    fixture: "Danish Gambit",
    id: "danish-gambit",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A classical open-game gambit where White offers c3 and sometimes a second pawn to accelerate bishop development and attack the black king.",
    whiteSummary: "Use the open diagonals immediately, develop every piece with tempo and avoid entering a quiet ending while material remains sacrificed.",
    blackSummary: "Return material when useful to blunt the bishops, complete development and force White to prove compensation without direct attacking lines.",
  },
  {
    family: "Danish Gambit Declined",
    fixture: "Danish Gambit Declined: Sörensen Defense",
    id: "danish-gambit-declined",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A Danish branch where Black avoids accepting the full pawn offer, reducing White's direct development compensation and keeping a more solid centre.",
    whiteSummary: "Use the extra development or central space gained from the declined offer to build a sound initiative without forcing sacrifices.",
    blackSummary: "Decline while challenging White's centre, complete development and avoid giving White a free attacking setup simply by refusing material.",
  },
  {
    family: "Fried Fox Defense",
    fixture: "Fried Fox Defense",
    id: "fried-fox-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A highly unorthodox defense with early kingside pawn or king exposure, creating immediate weaknesses and relying mostly on surprise and tactical complications.",
    whiteSummary: "Open the centre and develop rapidly toward the exposed king, keeping tactics simple and forcing the defense to justify its weaknesses.",
    blackSummary: "Seek concrete counterplay immediately and prioritize king shelter; quiet play usually leaves the early concessions without compensation.",
  },
  {
    family: "King's Gambit",
    fixture: "King's Gambit",
    id: "king-s-gambit",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A classical 1.e4 e5 2.f4 gambit family where White challenges the e5 pawn and offers kingside material for central control and rapid attacking development.",
    whiteSummary: "Use f4 to remove or undermine e5, develop quickly and keep the initiative more important than immediate material recovery.",
    blackSummary: "Challenge e4 and the exposed king, accept or decline according to the line and avoid passive defense that lets White build a free attack.",
  },
  {
    family: "Lemming Defense",
    fixture: "Lemming Defense",
    id: "lemming-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare offbeat defense using unusual early piece placement for surprise value while conceding some natural central development.",
    whiteSummary: "Take central space and develop efficiently, limiting the oddly placed piece before it can reroute.",
    blackSummary: "Give the unusual piece a concrete role quickly and strike at the centre so the move order creates activity rather than a lasting loss of time.",
  },
  {
    family: "Saragossa Opening",
    fixture: "Saragossa Opening",
    id: "saragossa-opening",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A quiet 1.c3 opening that prepares d4 and keeps e4 available, but develops no piece and allows Black broad central choice.",
    whiteSummary: "Use c3 to establish d4 promptly and develop naturally, avoiding a passive setup where the first move only blocks the knight.",
    blackSummary: "Claim central space and challenge d4/e4 as White builds the pawn centre, exploiting the slightly slower piece development.",
  },
];
