import type { OpeningKnowledgeCompletionFamily } from './openingKnowledge.completion.shared';

export const OPENING_KNOWLEDGE_COMPLETION_BATCH_1: readonly OpeningKnowledgeCompletionFamily[] = [
  {
    family: "King's Gambit Accepted",
    fixture: "King's Gambit Accepted",
    id: "king-s-gambit-accepted",
    kind: "FULL",
    confidence: "HIGH",
    orientation: "A forcing open-game family where Black accepts the f-pawn and White trades material for central control, rapid development and attacking chances against the king.",
    whiteSummary: "Use the development lead immediately: occupy the centre, bring pieces toward the kingside and recover material only when it does not cost the initiative.",
    blackSummary: "Consolidate the extra pawn without falling behind in development, return material when useful, and challenge White's centre before the attack becomes coordinated.",
  },
  {
    family: "Queen's Pawn Game",
    fixture: "Queen's Pawn Game",
    id: "queen-s-pawn-game",
    kind: "FULL",
    confidence: "HIGH",
    orientation: "A broad 1.d4 family built around flexible development and central control, often reaching London, Colle, Torre or transpositional structures without an immediate c4 confrontation.",
    whiteSummary: "Develop harmoniously, keep e4 or c4 as the main central break, and use the chosen piece setup to support the resulting pawn structure.",
    blackSummary: "Contest the centre with ...d5, ...c5 or ...e5 according to the move order and avoid allowing White a comfortable, uncontested setup.",
  },
  {
    family: "Indian Defense",
    fixture: "Indian Defense",
    id: "indian-defense",
    kind: "FULL",
    confidence: "HIGH",
    orientation: "A flexible 1.d4 Nf6 umbrella in which Black delays committing the central pawns and keeps several Indian and hypermodern transpositions available.",
    whiteSummary: "Use the extra central space responsibly, complete development and choose e4 or c4 structures that restrict Black's breaks.",
    blackSummary: "Pressure White's centre with pieces first, then choose the correct ...d5, ...c5 or ...e5 break rather than committing the pawn structure too early.",
  },
  {
    family: "King's Gambit Declined",
    fixture: "King's Gambit Declined: Classical Variation",
    id: "king-s-gambit-declined",
    kind: "FULL",
    confidence: "HIGH",
    orientation: "An open-game family where Black refuses White's f-pawn offer and instead challenges the centre or develops while White retains kingside space and attacking possibilities.",
    whiteSummary: "Use the f4 pawn as space and support for e5 or kingside play, while completing development before launching an attack.",
    blackSummary: "Exploit the time White spent on f4 by developing quickly, striking at e4 and the centre, and avoiding passive defense of the kingside.",
  },
  {
    family: "Scotch Game",
    fixture: "Scotch Game",
    id: "scotch-game",
    kind: "FULL",
    confidence: "HIGH",
    orientation: "An open-game family in which White plays an early d4 to clarify the centre and create immediate piece activity instead of maintaining the closed e4-e5 tension.",
    whiteSummary: "Use the open centre and lead in space to develop with tempo, keep the d-file and central squares active, and avoid unnecessary queen moves.",
    blackSummary: "Attack White's central pieces with active development, seek equality through pressure on d4/e4, and use timely ...d5 when it can be achieved safely.",
  },
  {
    family: "Petrov's Defense",
    fixture: "Petrov's Defense",
    id: "petrov-s-defense",
    kind: "FULL",
    confidence: "HIGH",
    orientation: "A symmetrical open-game defense where Black counterattacks e4 with ...Nf6 rather than simply defending e5, often leading to early exchanges and structurally balanced positions.",
    whiteSummary: "Preserve a small initiative through active development, central space and precise move order rather than forcing an attack in a symmetrical structure.",
    blackSummary: "Neutralize White's initiative by accurate development, challenge the centre promptly and avoid tactical shortcuts that undermine the normally solid structure.",
  },
  {
    family: "Four Knights Game",
    fixture: "Four Knights Game",
    id: "four-knights-game",
    kind: "FULL",
    confidence: "HIGH",
    orientation: "A classical open-game family where both sides develop the knights early and the struggle turns on which side first creates an effective central or flank imbalance.",
    whiteSummary: "Choose a purposeful break such as d4, Bb5 pressure or f4 only after development supports it, and avoid drifting in a fully symmetrical setup.",
    blackSummary: "Meet White's first imbalance actively, contest d4/e4 and use piece pressure or ...d5 to prevent a risk-free space advantage.",
  },
  {
    family: "Zukertort Opening",
    fixture: "Zukertort Opening",
    id: "zukertort-opening",
    kind: "FULL",
    confidence: "HIGH",
    orientation: "A flexible Nf3-first opening family that keeps d4, c4, g3 and e4 structures available and often reaches Réti, English or queen-pawn positions by transposition.",
    whiteSummary: "Preserve move-order flexibility while building a coherent centre; use the knight development to wait for Black's commitment before choosing the pawn structure.",
    blackSummary: "Claim useful central space while White delays commitment, but keep the structure flexible enough to meet c4, d4 or e4 transpositions.",
  },
  {
    family: "Scandinavian Defense",
    fixture: "Scandinavian Defense",
    id: "scandinavian-defense",
    kind: "FULL",
    confidence: "HIGH",
    orientation: "An immediate 1...d5 challenge to e4 that trades central tension for active piece play, often at the cost of exposing Black's queen to tempi after exd5.",
    whiteSummary: "Use development with tempo against the exposed queen, build a healthy centre and avoid overextending merely to chase it.",
    blackSummary: "Complete development after the early central exchange, place the queen safely and use the open d-file and pressure on d4/e4 for active counterplay.",
  },
  {
    family: "Philidor Defense",
    fixture: "Philidor Defense",
    id: "philidor-defense",
    kind: "FULL",
    confidence: "HIGH",
    orientation: "A compact e4-e5 defense where Black supports e5 with ...d6 and accepts less space in exchange for a resilient centre and later counterbreaks.",
    whiteSummary: "Build the broad centre with d4, develop actively and use the space advantage before Black achieves ...d5 or ...f5 counterplay.",
    blackSummary: "Avoid pure passivity: develop the kingside, challenge White's centre with ...d5 or ...f5 when prepared, and free the light-squared bishop.",
  },
  {
    family: "Nimzowitsch Defense",
    fixture: "Nimzowitsch Defense",
    id: "nimzowitsch-defense",
    kind: "FULL",
    confidence: "HIGH",
    orientation: "An offbeat but flexible 1...Nc6 response to e4 that develops immediately while inviting White to occupy the centre before Black decides how to attack it.",
    whiteSummary: "Take central space without overextending, develop normally and be ready to meet ...d5 or ...e5 breaks with a stable pawn centre.",
    blackSummary: "Use the early knight to pressure d4/e5, challenge White's centre promptly and avoid letting the knight become a target without gaining central counterplay.",
  },
  {
    family: "Bishop's Opening",
    fixture: "Bishop's Opening",
    id: "bishop-s-opening",
    kind: "FULL",
    confidence: "HIGH",
    orientation: "An open-game family where White develops Bc4 before committing the king's knight, preserving options for d3, f4 and rapid kingside activity.",
    whiteSummary: "Use the active bishop and flexible knight development to build pressure on f7 and prepare d4 or f4 under favorable conditions.",
    blackSummary: "Develop with tempo against the bishop when possible, contest the centre and avoid weakening f7 while White's pieces are aimed at the kingside.",
  },
  {
    family: "Vienna Game",
    fixture: "Vienna Game",
    id: "vienna-game",
    kind: "FULL",
    confidence: "HIGH",
    orientation: "An open-game family based on an early Nc3, supporting e4 while keeping f4, d4 and quieter development options available.",
    whiteSummary: "Use Nc3 to support a timely f4 or d4 break, but finish development before opening the king's position.",
    blackSummary: "Challenge White's flexible centre with active development and central breaks, and exploit any premature f-pawn advance with pressure on e4 and the king.",
  },
  {
    family: "Modern Defense",
    fixture: "Modern Defense",
    id: "modern-defense",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A hypermodern defense where Black fianchettos the dark-squared bishop and initially allows White to build a broad centre before attacking it with pieces and pawn breaks.",
    whiteSummary: "Use the extra space to restrict Black, keep the centre well supported and avoid advancing so far that ...c5 or ...e5 can undermine it tactically.",
    blackSummary: "Complete the kingside fianchetto, pressure the centre and time ...c5, ...e5 or ...b5 so White's space becomes a target rather than a permanent advantage.",
  },
  {
    family: "King's Pawn Game",
    fixture: "King's Pawn Game",
    id: "king-s-pawn-game",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A broad 1.e4 e5 family where both sides fight directly for the centre and rapid development, with many branches transposing into classical open games.",
    whiteSummary: "Develop quickly, preserve the e4 centre and use d4 when it opens lines for better-placed pieces.",
    blackSummary: "Contest e4 and d4 with pieces and pawns, complete development before grabbing material and seek equality through central activity.",
  },
  {
    family: "Pterodactyl Defense",
    fixture: "Pterodactyl Defense",
    id: "pterodactyl-defense",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A Modern/Dragon-style setup combining a kingside fianchetto with early ...c5 and often ...Qa5 pressure, aiming for active counterplay against White's centre.",
    whiteSummary: "Build the centre while watching the a5-e1 diagonal and queenside tactics; develop before trying to punish Black's unusual queen placement.",
    blackSummary: "Use the fianchetto bishop, ...c5 pressure and queen activity to provoke weaknesses, but do not let early queen play delay development or king safety.",
  },
  {
    family: "Van Geet Opening",
    fixture: "Van Geet Opening",
    id: "van-geet-opening",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "An offbeat 1.Nc3 opening that develops a piece while keeping e4, d4 and flank transpositions open, at the cost of sometimes blocking the c-pawn.",
    whiteSummary: "Use the flexible knight to support e4 or d5 pressure and choose a centre that justifies the early Nc3 placement.",
    blackSummary: "Claim central space and ask the c3-knight what role it has; challenge White before the opening transposes into a comfortable standard setup.",
  },
  {
    family: "Bird Opening",
    fixture: "Bird Opening",
    id: "bird-opening",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A flank opening with an early f4 that resembles a Dutch Defense with colors reversed, gaining kingside space while slightly loosening White's king.",
    whiteSummary: "Build around e3, Nf3 and a kingside fianchetto or e4 break, using the f-pawn as space rather than forcing an immediate attack.",
    blackSummary: "Strike at the centre with ...d5 or ...e5, exploit the weakened e1-h4 diagonal and king, and avoid drifting into a passive reversed-Dutch structure.",
  },
  {
    family: "Pirc Defense",
    fixture: "Pirc Defense",
    id: "pirc-defense",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A hypermodern defense where Black allows e4 and d4, develops with ...Nf6 and ...g6, then attacks the centre rather than occupying it immediately.",
    whiteSummary: "Use the space advantage to develop aggressively while keeping d4/e4 supported against ...c5 or ...e5 breaks.",
    blackSummary: "Complete development, pressure the centre and choose the right pawn break before White converts space into a lasting kingside initiative.",
  },
  {
    family: "Nimzo-Indian Defense",
    fixture: "Nimzo-Indian Defense",
    id: "nimzo-indian-defense",
    kind: "DESCRIPTION_ONLY",
    confidence: "MEDIUM",
    orientation: "A major 1.d4 defense where ...Bb4 pins the c3-knight and lets Black trade the bishop pair for structural control, dark-square pressure or rapid development.",
  },
  {
    family: "Polish Opening",
    fixture: "Polish Opening",
    id: "polish-opening",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A flank opening with an early b4 that gains queenside space and prepares Bb2 pressure while allowing Black to occupy the centre.",
    whiteSummary: "Support the b-pawn, develop the bishop to b2 and attack the centre from the flank rather than spending more tempi on pawn expansion.",
    blackSummary: "Take central space, challenge b4 with ...a5 or ...e5 ideas when appropriate and use the time White spent on the flank to develop faster.",
  },
  {
    family: "King's Indian Attack",
    fixture: "King's Indian Attack",
    id: "king-s-indian-attack",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A system opening based on Nf3, g3, Bg2, d3 and e4, usually aiming for a closed centre and kingside play rather than an immediate theoretical confrontation.",
    whiteSummary: "Establish e4, maneuver the kingside pieces toward an attack and use e5 or h4-h5 only when the centre is stable.",
    blackSummary: "Claim queenside and central space, open lines before White's kingside attack arrives and challenge e4 with ...d5 or ...c5 structures.",
  },
  {
    family: "Tarrasch Defense",
    fixture: "Tarrasch Defense",
    id: "tarrasch-defense",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "An active Queen's Gambit defense where Black uses ...c5 to challenge d4 early, often accepting an isolated queen's pawn in return for open lines and piece activity.",
    whiteSummary: "Pressure the isolated d-pawn, trade active pieces when favorable and prevent Black from converting activity into a kingside initiative.",
    blackSummary: "Use the IQP as a source of central space and open files, keep pieces active and seek ...d4 or tactical activity before simplification exposes the pawn.",
  },
  {
    family: "Blackmar-Diemer Gambit Accepted",
    fixture: "Blackmar-Diemer Gambit Accepted",
    id: "blackmar-diemer-gambit-accepted",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A queen-pawn gambit family where Black accepts the offered pawn and White seeks compensation through rapid development, open files and direct attacking chances.",
    whiteSummary: "Develop with maximum tempo, use the open f-file/central lines and avoid slow material-recovery moves that surrender the initiative.",
    blackSummary: "Consolidate the extra material by completing development, return a pawn if needed to blunt the attack and trade attacking pieces when safe.",
  },
  {
    family: "Bogo-Indian Defense",
    fixture: "Bogo-Indian Defense",
    id: "bogo-indian-defense",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A solid Indian defense where Black gives an early ...Bb4+ check, often exchanging or retreating the bishop to influence White's development and central structure.",
    whiteSummary: "Use the bishop pair or extra central space if granted, develop smoothly and avoid accepting structural concessions without compensating activity.",
    blackSummary: "Use the check to disrupt White's ideal setup, control e4 and seek a sound ...d5 or ...c5 structure without conceding unnecessary space.",
  },
  {
    family: "Grob Opening",
    fixture: "Grob Opening",
    id: "grob-opening",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A provocative 1.g4 flank opening that gains kingside space and can support Bg2, but weakens the king and leaves the g-pawn exposed.",
    whiteSummary: "Use the g-pawn to justify quick bishop development and central counterplay; do not make further pawn moves while the king remains unsafe.",
    blackSummary: "Occupy the centre, target g4 and the weakened dark squares, and open lines before White can turn the flank space into active piece play.",
  },
  {
    family: "Hungarian Opening",
    fixture: "Hungarian Opening",
    id: "hungarian-opening",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A flexible 1.g3 opening that prepares a kingside fianchetto and postpones the central pawn commitment, often transposing to Réti or English structures.",
    whiteSummary: "Fianchetto quickly, choose d4, c4 or e4 according to Black's setup and use move-order flexibility rather than passive waiting.",
    blackSummary: "Claim useful central space and restrict the bishop on g2, while keeping enough flexibility to meet White's eventual central break.",
  },
  {
    family: "Queen's Indian Defense",
    fixture: "Queen's Indian Defense",
    id: "queen-s-indian-defense",
    kind: "DESCRIPTION_ONLY",
    confidence: "MEDIUM",
    orientation: "A classical Indian defense where Black uses ...b6 and ...Bb7 to control e4 and restrain White's centre while maintaining a flexible pawn structure.",
  },
  {
    family: "Blackmar-Diemer Gambit",
    fixture: "Blackmar-Diemer Gambit",
    id: "blackmar-diemer-gambit",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "An aggressive queen-pawn gambit where White offers the e-pawn after d4 and e4 in exchange for rapid development and attacking lines.",
    whiteSummary: "Treat development and initiative as the compensation: activate every piece, use the f-file and avoid drifting into an endgame a pawn down.",
    blackSummary: "Accept only if the extra pawn can be defended without paralysis; otherwise return material to complete development and neutralize White's attack.",
  },
  {
    family: "Center Game",
    fixture: "Center Game",
    id: "center-game",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "An open-game family where White plays d4 early and often recaptures with the queen, opening lines immediately but exposing the queen to development with tempo.",
    whiteSummary: "Use the open centre to develop rapidly and place the queen where it supports activity without becoming a repeated target.",
    blackSummary: "Develop pieces with tempo against the queen, contest d4/e4 and avoid grabbing extra material if it leaves the king in the centre.",
  },
];
