import type { OpeningKnowledgeCompletionFamily } from './openingKnowledge.completion.shared';

export const OPENING_KNOWLEDGE_COMPLETION_BATCH_2: readonly OpeningKnowledgeCompletionFamily[] = [
  {
    family: "Nimzo-Larsen Attack",
    fixture: "Nimzo-Larsen Attack",
    id: "nimzo-larsen-attack",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A hypermodern flank opening based on b3 and Bb2, aiming long-range pressure at the centre while keeping the pawn structure flexible.",
    whiteSummary: "Use the bishop on b2 to pressure e5/g7, choose e3/f4 or d4 structures that complement it and avoid allowing the centre to close the diagonal permanently.",
    blackSummary: "Occupy the centre, blunt the b2 bishop when useful and be ready to return central space through exchanges before White's pressure becomes concrete.",
  },
  {
    family: "Vienna Gambit",
    fixture: "Vienna Gambit, with Max Lange Defense",
    id: "vienna-gambit",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "An aggressive Vienna branch where White advances f4 to challenge e5 and seek rapid kingside initiative at the cost of weakening the king.",
    whiteSummary: "Open lines while ahead in activity, support e4 and bring pieces toward the kingside before the f-pawn advance becomes a target.",
    blackSummary: "Challenge e4 and f4 immediately, return material if necessary to finish development and use the weakened king as a long-term target.",
  },
  {
    family: "Latvian Gambit",
    fixture: "Latvian Gambit",
    id: "latvian-gambit",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A sharp 1.e4 e5 2.Nf3 f5 countergambit where Black attacks the centre immediately but weakens the king and often accepts objective risk for initiative.",
    whiteSummary: "Exploit the loose king and central weaknesses with accurate development; accept material only when it does not expose your own king to tactics.",
    blackSummary: "Keep the initiative concrete, develop with threats and avoid quiet play that leaves the f-pawn advance as a permanent weakness.",
  },
  {
    family: "Ponziani Opening",
    fixture: "Ponziani Opening",
    id: "ponziani-opening",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "An open-game family where White plays c3 early to prepare d4 and build a strong centre, while temporarily blocking the natural c3 square for the knight.",
    whiteSummary: "Prepare d4 efficiently, develop the queenside without losing time and use the centre before Black breaks it with ...d5 or ...f5.",
    blackSummary: "Challenge the c3-d4 construction immediately with central breaks and active piece play, exploiting White's slightly slower development.",
  },
  {
    family: "Neo-Grünfeld Defense",
    fixture: "Neo-Grünfeld Defense: Classical Variation",
    id: "neo-gr-nfeld-defense",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A Grünfeld-related defense against White's kingside fianchetto, where Black attacks the d4 centre with pieces and ...c5 while White seeks durable spatial control.",
    whiteSummary: "Use the fianchetto to reinforce the centre, keep d4 stable and convert space into queenside or central pressure.",
    blackSummary: "Pressure d4 with the g7 bishop, ...c5 and active pieces, seeking dynamic counterplay before White consolidates the centre.",
  },
  {
    family: "Slav Defense",
    fixture: "Slav Defense",
    id: "slav-defense",
    kind: "DESCRIPTION_ONLY",
    confidence: "MEDIUM",
    orientation: "A major Queen's Gambit defense where ...c6 supports d5 while keeping Black's light-squared bishop flexible and the pawn structure fundamentally sound.",
  },
  {
    family: "Old Indian Defense",
    fixture: "Old Indian Defense",
    id: "old-indian-defense",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A compact Indian defense with ...d6 and ...e5 where Black builds a solid centre without the immediate kingside fianchetto of the King's Indian.",
    whiteSummary: "Use the extra space to develop naturally and prepare d5 or queenside expansion before Black achieves freeing breaks.",
    blackSummary: "Complete development behind the compact centre and prepare ...c6, ...c5 or ...f5 so the position does not become permanently cramped.",
  },
  {
    family: "Rat Defense",
    fixture: "Rat Defense: Accelerated Gurgenidze",
    id: "rat-defense",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A flexible family of ...d6, ...Nf6 and related move orders that delays a fixed pawn structure and frequently transposes into Pirc, Modern or Indian positions.",
    whiteSummary: "Claim central space but keep it well defended, watching for transpositions and timely ...e5 or ...c5 attacks.",
    blackSummary: "Use the flexible move order to choose the most effective central break after White commits, rather than remaining passive behind the first rank.",
  },
  {
    family: "Trompowsky Attack",
    fixture: "Trompowsky Attack",
    id: "trompowsky-attack",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A 1.d4 Nf6 2.Bg5 system that pins or provokes the f6-knight and can create doubled pawns, rapid e4 expansion or unusual piece structures.",
    whiteSummary: "Use the bishop sortie to gain a structural or central concession, then develop quickly instead of trying to win material with the bishop alone.",
    blackSummary: "Challenge the bishop and centre with active play, accept structural damage only for concrete compensation and avoid allowing an effortless e4 centre.",
  },
  {
    family: "Blackmar-Diemer Gambit Declined",
    fixture: "Blackmar-Diemer Gambit Declined: Brombacher Countergambit",
    id: "blackmar-diemer-gambit-declined",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A family where Black refuses or sidesteps the Blackmar-Diemer pawn offer, reducing White's direct compensation and steering toward a more conventional queen-pawn centre.",
    whiteSummary: "Use the extra central space or tempo from the declined gambit to complete development and choose a sound e4/d4 structure.",
    blackSummary: "Decline in a way that challenges White's centre, not merely retreats; develop quickly and prevent White from gaining a free attacking setup.",
  },
  {
    family: "Englund Gambit",
    fixture: "Englund Gambit",
    id: "englund-gambit",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A provocative 1.d4 e5 gambit where Black sacrifices or offers the e-pawn for rapid development, tactical pressure and practical surprise value.",
    whiteSummary: "Secure the extra pawn only if development remains safe; otherwise return it and use the central advantage to neutralize Black's initiative.",
    blackSummary: "Develop with threats and open lines immediately, because the gambit compensation fades quickly if White consolidates.",
  },
  {
    family: "Latvian Gambit Accepted",
    fixture: "Latvian Gambit Accepted",
    id: "latvian-gambit-accepted",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A forcing Latvian branch where White accepts material and the position becomes a tactical race between White's extra pawn and Black's initiative against the centre and king.",
    whiteSummary: "Prioritize king safety and development over holding every pawn, and trade attacking pieces when it reduces Black's compensation.",
    blackSummary: "Keep lines open, develop with tempo and use threats against e4/f2 before White consolidates the material advantage.",
  },
  {
    family: "Kádas Opening",
    fixture: "Kádas Opening",
    id: "k-das-opening",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "An offbeat flank opening beginning with an early h-pawn move, gaining a little kingside space but contributing little to central development.",
    whiteSummary: "Avoid compounding the lost tempo; build a normal centre and develop pieces before using the h-pawn for further space or rook activity.",
    blackSummary: "Claim the centre and develop rapidly, treating the early flank move as a chance to seize space rather than a target that must be attacked immediately.",
  },
  {
    family: "Catalan Opening",
    fixture: "Catalan Opening",
    id: "catalan-opening",
    kind: "DESCRIPTION_ONLY",
    confidence: "MEDIUM",
    orientation: "A major queen-pawn system combining d4/c4 with a kingside fianchetto, using the g2 bishop for long-term pressure on the queenside and central dark squares.",
  },
  {
    family: "Owen Defense",
    fixture: "Owen Defense",
    id: "owen-defense",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A hypermodern 1...b6 defense where Black fianchettos the queen's bishop and attacks e4 from the long diagonal while conceding initial central space.",
    whiteSummary: "Build a strong but mobile centre, develop quickly and be ready to advance or exchange before the b7 bishop undermines e4.",
    blackSummary: "Use ...Bb7 to pressure e4, attack the centre with ...f5 or ...c5 when appropriate and avoid remaining passive behind the fianchetto.",
  },
  {
    family: "Richter-Veresov Attack",
    fixture: "Richter-Veresov Attack",
    id: "richter-veresov-attack",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A queen-pawn attacking system with Nc3 and Bg5 that supports e4 and rapid development, often creating open central play outside mainstream Queen's Gambit structures.",
    whiteSummary: "Use the developed pieces to achieve e4 under good conditions and keep the initiative rather than making repeated minor-piece moves.",
    blackSummary: "Challenge e4 and d4 promptly, question the bishop on g5 and exploit the c3-knight's placement if White's centre cannot be maintained.",
  },
  {
    family: "Englund Gambit Declined",
    fixture: "Englund Gambit Declined",
    id: "englund-gambit-declined",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A family where White avoids taking the Englund pawn and keeps a compact centre, reducing Black's intended gambit initiative but often entering unusual move orders.",
    whiteSummary: "Use the preserved centre to develop naturally and punish Black only after piece coordination is complete.",
    blackSummary: "Turn the declined gambit into active central development and avoid spending more tempi trying to force tactics that White has sidestepped.",
  },
  {
    family: "Ware Opening",
    fixture: "Ware Opening",
    id: "ware-opening",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "An offbeat 1.a4 flank opening that gains queenside space and may prepare Ra3 or b4, but does not contribute directly to central development.",
    whiteSummary: "Return quickly to central development and use the a-pawn only when it supports a concrete queenside structure.",
    blackSummary: "Claim the centre and develop normally, using the extra tempo to build activity rather than chasing the advanced a-pawn prematurely.",
  },
  {
    family: "English Defense",
    fixture: "English Defense",
    id: "english-defense",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A hypermodern queen-pawn defense with ...b6 and ...Bb7, often combined with ...f5 or ...e6, attacking White's centre from the flank.",
    whiteSummary: "Use the central space to restrict the b7 bishop and prepare e4 while watching for ...Bb4+ and ...f5 counterplay.",
    blackSummary: "Pressure e4 and the long diagonal, develop quickly and choose ...f5, ...c5 or ...e5 according to White's centre.",
  },
  {
    family: "Danish Gambit Accepted",
    fixture: "Danish Gambit Accepted",
    id: "danish-gambit-accepted",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A classical open-game gambit where Black accepts one or two queenside pawns while White gains rapid bishop development and open attacking diagonals.",
    whiteSummary: "Use the development lead immediately against f7 and the centre, and recover material only when it does not surrender the initiative.",
    blackSummary: "Return material if needed to finish development, blunt the bishops and reach a position where the extra pawn matters more than White's activity.",
  },
  {
    family: "Lion Defense",
    fixture: "Lion Defense",
    id: "lion-defense",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A compact Philidor/Pirc-style setup where Black develops behind ...d6 and ...e5 or related structures, aiming to absorb White's centre and counterattack later.",
    whiteSummary: "Use the space advantage to complete development, open the centre before Black reorganizes and watch for kingside counterplay.",
    blackSummary: "Coordinate the compact pieces, prepare freeing ...d5 or ...f5 breaks and avoid a purely defensive setup with no central counterplay.",
  },
  {
    family: "Torre Attack",
    fixture: "Torre Attack: Classical Defense",
    id: "torre-attack",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A queen-pawn system with Nf3 and Bg5 that develops simply, restrains ...e5 and often prepares e3, Bd3 and a later e4 break.",
    whiteSummary: "Complete the setup efficiently and use e4 or c4 to turn the easy development into a concrete central advantage.",
    blackSummary: "Challenge the bishop and d4 centre, seek ...c5 or ...e5 breaks and prevent White from reaching the ideal setup without concessions.",
  },
  {
    family: "Barnes Opening",
    fixture: "Barnes Opening",
    id: "barnes-opening",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "An eccentric 1.f3 opening that supports e4 but weakens the king and delays normal development, making central discipline especially important.",
    whiteSummary: "Use f3 only to support a stable e4 centre, develop immediately and keep the king safe rather than launching an early pawn attack.",
    blackSummary: "Open the centre and develop rapidly toward the weakened king, especially exploiting the e1-h4 diagonal and slow kingside development.",
  },
  {
    family: "Three Knights Opening",
    fixture: "Three Knights Opening",
    id: "three-knights-opening",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "An open-game family where three knights are developed early and one side delays the fourth, creating flexible transpositions into Four Knights, Scotch or Italian structures.",
    whiteSummary: "Use the move-order flexibility to choose a purposeful central break before the position becomes a passive imitation of the Four Knights.",
    blackSummary: "Develop actively and exploit whichever minor piece White has delayed, challenging the centre before White completes the ideal setup.",
  },
  {
    family: "Rubinstein Opening",
    fixture: "Rubinstein Opening",
    id: "rubinstein-opening",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A quiet queen-pawn opening family emphasizing sound central support, flexible minor-piece development and transpositional possibilities rather than an immediate forcing line.",
    whiteSummary: "Build a coherent d4/e3 or c4 structure, improve the pieces and choose the central break only after Black's setup is clear.",
    blackSummary: "Claim equal central influence, avoid conceding a risk-free space edge and use ...c5 or ...e5 to prevent White from settling into a comfortable system.",
  },
  {
    family: "Van't Kruijs Opening",
    fixture: "Van't Kruijs Opening",
    id: "van-t-kruijs-opening",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A modest 1.e3 opening that keeps the centre flexible and prepares d4 or e4, but gives Black freedom to occupy central space first.",
    whiteSummary: "Use the flexible first move to transpose into a sound centre quickly; do not spend additional tempi on passive development.",
    blackSummary: "Take useful central space and make White prove the value of the waiting move, while keeping the position flexible enough for later breaks.",
  },
  {
    family: "Borg Defense",
    fixture: "Borg Defense",
    id: "borg-defense",
    kind: "FULL",
    confidence: "MEDIUM",
    orientation: "A provocative ...g5 defense that grabs kingside space at the cost of weakening dark squares and exposing Black's king before development.",
    whiteSummary: "Occupy the centre, attack the advanced g-pawn when convenient and open lines before Black can stabilize the kingside.",
    blackSummary: "Use the space gain to create concrete activity immediately; develop quickly and avoid further pawn moves that worsen king safety without compensation.",
  },
  {
    family: "Elephant Gambit",
    fixture: "Elephant Gambit",
    id: "elephant-gambit",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A sharp open-game countergambit with an early ...d5, where Black offers central material to accelerate development and challenge White's e4 pawn.",
    whiteSummary: "Meet the central break accurately, keep the king safe and return material if that neutralizes Black's initiative while preserving a structural edge.",
    blackSummary: "Use the open centre and development tempi aggressively; if the initiative fades, prioritize piece coordination over clinging to gambit compensation.",
  },
  {
    family: "Mieses Opening",
    fixture: "Mieses Opening",
    id: "mieses-opening",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A flexible 1.d3 opening that postpones central occupation and often aims for e4, g3 and a restrained kingside setup.",
    whiteSummary: "Use the quiet first move to build a sound e4 centre and develop efficiently rather than allowing Black permanent extra space.",
    blackSummary: "Claim the centre and restrict White's later e4 break, while staying alert to transpositions into King's Indian Attack or reversed Pirc structures.",
  },
  {
    family: "Mikenas Defense",
    fixture: "Mikenas Defense",
    id: "mikenas-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "An uncommon defense featuring early knight development and flexible central pawn placement, seeking piece pressure before fully defining the pawn structure.",
    whiteSummary: "Build a stable centre and use the space to restrict the advanced knight, developing without creating tactical targets.",
    blackSummary: "Justify the unusual knight placement with pressure and timely central breaks, avoiding repeated knight moves that concede development.",
  },
];
