import type { OpeningKnowledgeSource } from './openingKnowledge.types';

export const OPENING_KNOWLEDGE_SOURCES: readonly OpeningKnowledgeSource[] = [
  {
    id: 'project-editorial-rb-022',
    title: 'RB-022 reviewed project-original opening knowledge corpus',
    sourceRef: 'north-star/repertoire-builder/reports/RB-022-2026-08-01-static-opening-knowledge.md',
    sourceType: 'PROJECT_RESEARCH',
    license: 'PROJECT_ORIGINAL',
    retrievedAt: '2026-08-01',
  },
  {
    id: 'project-rb-021-foundation',
    title: 'RB-021 side-aware opening knowledge foundation',
    sourceRef: 'north-star/repertoire-builder/reports/RB-021-2026-07-31-opening-knowledge-foundation.md',
    sourceType: 'PROJECT_RESEARCH',
    license: 'PROJECT_ORIGINAL',
    retrievedAt: '2026-07-31',
  },
  {
    id: 'lichess-chess-openings',
    title: 'lichess-org/chess-openings',
    sourceRef: 'https://github.com/lichess-org/chess-openings',
    sourceType: 'DATASET',
    license: 'CC0-1.0',
    retrievedAt: '2026-07-31',
  },
  {
    id: 'lichess-sicilian-najdorf',
    title: 'Lichess opening reference: Sicilian Defense, Najdorf Variation',
    sourceRef: 'https://lichess.org/opening/Sicilian_Defense_Najdorf_Variation',
    sourceType: 'REFERENCE',
    license: 'REFERENCE_ONLY',
    retrievedAt: '2026-07-31',
  },
  {
    id: 'lichess-najdorf-english-attack',
    title: 'Lichess opening reference: Najdorf English Attack',
    sourceRef: 'https://lichess.org/opening/Sicilian_Defense_Najdorf_Variation_English_Attack',
    sourceType: 'REFERENCE',
    license: 'REFERENCE_ONLY',
    retrievedAt: '2026-07-31',
  },
  {
    id: 'lichess-najdorf-poisoned-pawn',
    title: 'Lichess opening reference: Najdorf Poisoned Pawn',
    sourceRef: 'https://lichess.org/opening/Sicilian_Defense_Najdorf_Variation_Poisoned_Pawn_Variation',
    sourceType: 'REFERENCE',
    license: 'REFERENCE_ONLY',
    retrievedAt: '2026-07-31',
  },
  {
    id: 'lichess-french-defense',
    title: 'Lichess opening reference: French Defense',
    sourceRef: 'https://lichess.org/opening/French_Defense',
    sourceType: 'REFERENCE',
    license: 'REFERENCE_ONLY',
    retrievedAt: '2026-07-31',
  },
  {
    id: 'lichess-english-opening',
    title: 'Lichess opening reference: English Opening',
    sourceRef: 'https://lichess.org/opening/English_Opening',
    sourceType: 'REFERENCE',
    license: 'REFERENCE_ONLY',
    retrievedAt: '2026-07-31',
  },
  {
    id: 'lichess-benko-gambit',
    title: 'Lichess opening reference: Benko Gambit',
    sourceRef: 'https://lichess.org/opening/Benko_Gambit',
    sourceType: 'REFERENCE',
    license: 'REFERENCE_ONLY',
    retrievedAt: '2026-07-31',
  },
  {
    id: 'lichess-evans-gambit-accepted',
    title: 'Lichess opening reference: Evans Gambit Accepted',
    sourceRef: 'https://lichess.org/opening/Italian_Game_Evans_Gambit_Accepted',
    sourceType: 'REFERENCE',
    license: 'REFERENCE_ONLY',
    retrievedAt: '2026-07-31',
  },
];
