import type { OpeningKnowledgeCompletionFamily } from './openingKnowledge.completion.shared';

export const OPENING_KNOWLEDGE_COMPLETION_BATCH_3: readonly OpeningKnowledgeCompletionFamily[] = [
  {
    family: "Sodium Attack",
    fixture: "Sodium Attack",
    id: "sodium-attack",
    kind: "FULL",
    confidence: "LOW",
    orientation: "An offbeat 1.Na3 opening that develops a knight to the rim, usually intending c4 or b5 while preserving the central pawns.",
    whiteSummary: "Re-route the knight purposefully and establish a normal centre quickly so the unusual first move does not become a lasting loss of time.",
    blackSummary: "Take central space and restrict the a3-knight's useful routes, but avoid overreacting to a piece that may transpose back into play.",
  },
  {
    family: "St. George Defense",
    fixture: "St. George Defense",
    id: "st-george-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "An offbeat ...a6 and often ...b5 defense that seeks queenside space and a fianchetto while conceding early central influence.",
    whiteSummary: "Occupy the centre and open it before Black's queenside setup becomes active, while keeping an eye on ...Bb7 pressure.",
    blackSummary: "Complete the queenside expansion efficiently, develop the bishop and challenge White's centre so the early flank tempi have a strategic purpose.",
  },
  {
    family: "Rapport-Jobava System",
    fixture: "Rapport-Jobava System",
    id: "rapport-jobava-system",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A modern queen-pawn system combining d4, Nc3 and Bf4, aiming for rapid development, e4 support and practical kingside pressure.",
    whiteSummary: "Use the active bishop and c3-knight to support e4 or Nb5 ideas, but stay sensitive to ...c5 and ...Bf5 challenges to the centre.",
    blackSummary: "Strike at d4 with ...c5, question the bishop and exploit the c3-knight's blockage of the c-pawn when White overcommits to kingside play.",
  },
  {
    family: "Portuguese Opening",
    fixture: "Portuguese Opening",
    id: "portuguese-opening",
    kind: "FULL",
    confidence: "LOW",
    orientation: "An unusual open-game family with early bishop activity that seeks immediate pressure and flexible central development rather than the most common knight-first move order.",
    whiteSummary: "Use the bishop's active placement to gain development and central leverage, avoiding repeated bishop moves that lose the initiative.",
    blackSummary: "Develop with tempo against the early bishop, contest the centre and make the unusual move order prove concrete value.",
  },
  {
    family: "Amar Opening",
    fixture: "Amar Opening",
    id: "amar-opening",
    kind: "FULL",
    confidence: "LOW",
    orientation: "An offbeat 1.Nh3 opening that develops the king's knight to the rim, often intending f4 or a later reroute while keeping central pawns flexible.",
    whiteSummary: "Give the h3-knight a clear route, establish a normal centre and avoid further slow moves that leave Black with a free initiative.",
    blackSummary: "Occupy the centre and limit the knight's useful squares, using the development advantage rather than trying to trap it at all costs.",
  },
  {
    family: "Blumenfeld Countergambit",
    fixture: "Blumenfeld Countergambit",
    id: "blumenfeld-countergambit",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A dynamic queen-pawn countergambit where Black offers a queenside pawn to build a mobile central mass and active piece play.",
    whiteSummary: "If accepting, blockade the central pawns and complete development before trying to exploit the extra material.",
    blackSummary: "Use the central pawns, open files and development lead aggressively; the compensation depends on activity rather than long-term material balance.",
  },
  {
    family: "Colle System",
    fixture: "Colle System: Pterodactyl Variation",
    id: "colle-system",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A solid queen-pawn system based on d4, Nf3, e3 and Bd3, usually preparing the e4 break and kingside activity from a compact setup.",
    whiteSummary: "Prepare e4 efficiently, place the pieces behind the central break and avoid allowing Black to equalize comfortably with ...c5 and active development.",
    blackSummary: "Challenge d4 early with ...c5 or ...e5, restrain the e4 break and use queenside space if White's setup becomes too automatic.",
  },
  {
    family: "King's Knight Opening",
    fixture: "King's Knight Opening",
    id: "king-s-knight-opening",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A classical king-pawn development family centered on Nf3, immediately pressuring e5 and preparing rapid castling and central play.",
    whiteSummary: "Use the knight pressure to support d4 and quick development, choosing the open-game branch that best preserves initiative.",
    blackSummary: "Defend or counterattack e5 actively, develop with tempo and contest d4 before White establishes a free central expansion.",
  },
  {
    family: "King's Pawn Opening",
    fixture: "King's Pawn Opening",
    id: "king-s-pawn-opening",
    kind: "FULL",
    confidence: "LOW",
    orientation: "The broad 1.e4 opening family, staking central space immediately and opening lines for the queen and king's bishop before the exact defense is known.",
    whiteSummary: "Use the central space to develop rapidly and adapt the pawn structure to Black's defense rather than forcing one setup against every reply.",
    blackSummary: "Challenge e4 and the light squares with an appropriate central counter, developing quickly enough that White cannot convert the first-move space into a lasting initiative.",
  },
  {
    family: "Anderssen's Opening",
    fixture: "Anderssen's Opening",
    id: "anderssen-s-opening",
    kind: "FULL",
    confidence: "LOW",
    orientation: "An offbeat 1.a3 opening that reserves b4 and removes a back-rank pawn while conceding the first move's normal central influence.",
    whiteSummary: "Use the waiting move to choose a favorable central setup quickly and only expand with b4 when it supports developed pieces.",
    blackSummary: "Take central space and develop normally, making White justify the flank tempo rather than spending time attacking a harmless pawn.",
  },
  {
    family: "Clemenz Opening",
    fixture: "Clemenz Opening",
    id: "clemenz-opening",
    kind: "FULL",
    confidence: "LOW",
    orientation: "An offbeat 1.h3 opening that creates luft and may support g4, but delays central occupation and can invite Black to seize space.",
    whiteSummary: "Build a normal centre immediately and use h3 only as a useful hook or king-safety detail later in the game.",
    blackSummary: "Claim the centre and develop actively, keeping the option to open lines if White follows the waiting move with more kingside pawn advances.",
  },
  {
    family: "Formation",
    fixture: "Formation: Hippopotamus Attack",
    id: "formation",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A family of deliberately restrained formations such as Hippopotamus-style setups, where one side concedes space and keeps several pawn breaks in reserve.",
    whiteSummary: "If using the restrained setup, coordinate pieces behind the pawn shell and choose a single timely break instead of remaining passive indefinitely.",
    blackSummary: "Use the space advantage to restrict counterbreaks, improve pieces and open the position before the compact formation becomes fully coordinated.",
  },
  {
    family: "Amazon Attack",
    fixture: "Amazon Attack",
    id: "amazon-attack",
    kind: "FULL",
    confidence: "LOW",
    orientation: "An offbeat queen-pawn attack featuring early queen activity to reinforce central or kingside ideas, gaining flexibility but risking tempi against the queen.",
    whiteSummary: "Use the queen to support a concrete central plan and develop pieces quickly so it does not become a repeated target.",
    blackSummary: "Develop with tempo against the queen when safe, contest the centre and avoid chasing it if doing so neglects your own king and development.",
  },
  {
    family: "Carr Defense",
    fixture: "Carr Defense",
    id: "carr-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare flank-pawn defense to 1.e4 that delays direct central contest and tries to create an unusual structure or surprise value.",
    whiteSummary: "Occupy the centre, develop rapidly and open lines before Black's flank move can be justified by counterplay.",
    blackSummary: "Use the unusual move to support a concrete setup quickly, then challenge e4; avoid spending additional tempi on flank pawns while underdeveloped.",
  },
  {
    family: "Goldsmith Defense",
    fixture: "Goldsmith Defense",
    id: "goldsmith-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare flank defense that spends an early tempo away from the centre, seeking surprise value but allowing White broad central choice.",
    whiteSummary: "Take central space with e4/d4 and develop efficiently, treating the unusual move as a tempo advantage rather than a tactical target.",
    blackSummary: "Complete development and attack the centre promptly so the early flank move becomes part of a coherent plan rather than a permanent loss of time.",
  },
  {
    family: "Horwitz Defense",
    fixture: "Horwitz Defense",
    id: "horwitz-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A flexible 1.d4 e6 defense that delays ...d5 and can transpose into French, Queen's Gambit, Indian or English Defense structures.",
    whiteSummary: "Use the move-order freedom to claim c4/e4 space while watching for transpositions and ...f5 or ...b6 setups.",
    blackSummary: "Choose the central structure after White commits, using ...d5, ...f5, ...c5 or ...b6 to challenge the centre without drifting into passivity.",
  },
  {
    family: "Mexican Defense",
    fixture: "Mexican Defense",
    id: "mexican-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "An uncommon 1.d4 Nf6 2.c4 Nc6 setup where Black develops the queen's knight early and often aims for ...e5 pressure on the centre.",
    whiteSummary: "Build the central pawn mass while restricting the c6-knight and prepare d5 only when it gains space without creating tactical targets.",
    blackSummary: "Use the active knight and ...e5 break to pressure d4, accepting less conventional piece placement in exchange for immediate central play.",
  },
  {
    family: "Polish Defense",
    fixture: "Polish Defense",
    id: "polish-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A hypermodern 1.d4 b5 defense that gains queenside space and prepares ...Bb7 while conceding the centre and creating a potentially vulnerable b-pawn.",
    whiteSummary: "Occupy the centre, challenge b5 when development permits and limit the b7 bishop's influence with a stable pawn chain.",
    blackSummary: "Use queenside space and the long diagonal actively, strike at the centre and avoid defending the b-pawn passively if activity can be gained instead.",
  },
  {
    family: "Slav Indian",
    fixture: "Slav Indian",
    id: "slav-indian",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A hybrid queen-pawn setup combining ...Nf6 and ...c6, keeping Slav solidity while retaining Indian move-order flexibility.",
    whiteSummary: "Use the extra space to press d5/e5 and develop before Black chooses between ...d5, ...g6 or ...e6 structures.",
    blackSummary: "Keep the solid c6 base while selecting the most active central setup; do not allow the hybrid move order to become cramped.",
  },
  {
    family: "Zukertort Defense",
    fixture: "Zukertort Defense: Kingside Variation",
    id: "zukertort-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A flexible knight-first defense that delays the central pawn commitment and keeps several classical or hypermodern transpositions available.",
    whiteSummary: "Use the extra central choice to build space while staying alert to transpositions and timely counterbreaks.",
    blackSummary: "Develop the knight with purpose, then challenge the centre promptly once White reveals the pawn structure.",
  },
  {
    family: "English Orangutan",
    fixture: "English Orangutan",
    id: "english-orangutan",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A queenside flank system combining English-style central restraint with an early b-pawn expansion, aiming for space and pressure on the long diagonal.",
    whiteSummary: "Support the queenside space with piece development and c4/e3 pressure rather than pushing more pawns without a centre.",
    blackSummary: "Occupy the centre and challenge the advanced b-pawn or long diagonal before White consolidates queenside space.",
  },
  {
    family: "Kangaroo Defense",
    fixture: "Kangaroo Defense",
    id: "kangaroo-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A queen-pawn defense using an early ...Bb4+ check to disturb White's development and steer toward Bogo-Indian or related structures.",
    whiteSummary: "Meet the check without unnecessary structural concessions, then use the bishop pair or centre if Black exchanges on d2/c3.",
    blackSummary: "Use the check to influence White's setup, then challenge d4 with ...Nf6, ...c5 or ...d5 and avoid retreating into passivity.",
  },
  {
    family: "Marienbad System",
    fixture: "Marienbad System",
    id: "marienbad-system",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A quiet queen-pawn system built around sound development and a restrained centre, often leading to positional maneuvering and transpositions.",
    whiteSummary: "Use the compact setup to prepare a purposeful c4 or e4 break and improve pieces before fixing the pawn structure.",
    blackSummary: "Challenge the restrained centre early enough that White cannot complete the ideal setup without making a concession.",
  },
  {
    family: "Ware Defense",
    fixture: "Ware Defense",
    id: "ware-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "An offbeat defense with an early a-pawn move, gaining queenside space while delaying direct central development.",
    whiteSummary: "Take the centre and develop quickly, opening lines if Black spends further tempi on queenside pawns.",
    blackSummary: "Use the a-pawn move to support a coherent queenside plan quickly and contest the centre before White's space advantage becomes permanent.",
  },
  {
    family: "Hippopotamus Defense",
    fixture: "Hippopotamus Defense",
    id: "hippopotamus-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A deliberately compact defense with pawns on the third rank and pieces behind them, conceding space in order to retain multiple central and flank breaks.",
    whiteSummary: "Use the large space advantage to restrict Black's breaks, improve pieces and open the centre when Black is least coordinated.",
    blackSummary: "Stay flexible and choose the correct ...e5, ...c5, ...f5 or ...b5 break; passive waiting without a counterbreak leaves the position strategically difficult.",
  },
  {
    family: "Pseudo Queen's Indian Defense",
    fixture: "Pseudo Queen's Indian Defense",
    id: "pseudo-queen-s-indian-defense",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A Queen's Indian-style setup reached by a nonstandard move order, using ...b6 and ...Bb7 to pressure the centre without committing to the canonical sequence.",
    whiteSummary: "Use the move-order difference to claim space if available while respecting the b7 bishop's pressure on e4.",
    blackSummary: "Preserve the Queen's Indian goals of e4 control, active ...c5/...d5 breaks and flexible piece placement despite the transposed move order.",
  },
  {
    family: "Duras Gambit",
    fixture: "Duras Gambit",
    id: "duras-gambit",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare 1.e4 f5 countergambit where Black immediately attacks e4 but seriously weakens the king and the e6-g6 dark squares.",
    whiteSummary: "Use the central and king-safety weaknesses with rapid development, accepting material only when it does not allow dangerous counterplay.",
    blackSummary: "Keep the initiative tactical and develop with tempo; if White consolidates, the weakened king and f-pawn investment become long-term liabilities.",
  },
  {
    family: "Irish Gambit",
    fixture: "Irish Gambit",
    id: "irish-gambit",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare open-game gambit that creates early tactical complications by giving material or central stability for development and surprise value.",
    whiteSummary: "Prioritize development and king safety, return material if necessary and force the gambit side to prove concrete compensation.",
    blackSummary: "Use the temporary lead in activity immediately and avoid drifting into a quiet position where the material deficit dominates.",
  },
  {
    family: "Amsterdam Attack",
    fixture: "Amsterdam Attack",
    id: "amsterdam-attack",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare flank/central attack that uses an unusual early setup to create surprise and flexible attacking chances rather than occupying the centre conventionally.",
    whiteSummary: "Turn the unusual move order into a coherent central plan quickly and develop pieces before beginning a flank attack.",
    blackSummary: "Claim central space and challenge the setup at its base, avoiding speculative pawn-chasing that gives the attacker free development.",
  },
  {
    family: "Canard Opening",
    fixture: "Canard Opening",
    id: "canard-opening",
    kind: "FULL",
    confidence: "LOW",
    orientation: "A rare queen-pawn sideline with an unusual early move order designed to create asymmetry and sidestep mainstream theory.",
    whiteSummary: "Use the surprise value to reach a sound centre and complete development rather than relying on the opponent remaining unfamiliar.",
    blackSummary: "Respond with principled central play, develop quickly and make the unusual move order justify any loss of time or structural concession.",
  },
];
