DROP TABLE IF EXISTS "LineSubline";

ALTER TABLE "Line" DROP COLUMN IF EXISTS "passedCount";
ALTER TABLE "Line" DROP COLUMN IF EXISTS "failedCount";
ALTER TABLE "Line" DROP COLUMN IF EXISTS "totalAttempts";
ALTER TABLE "Line" DROP COLUMN IF EXISTS "lastTrainedAt";

ALTER TABLE "MoveNode" DROP COLUMN IF EXISTS "timesSeen";
ALTER TABLE "MoveNode" DROP COLUMN IF EXISTS "correctCount";
ALTER TABLE "MoveNode" DROP COLUMN IF EXISTS "incorrectCount";
ALTER TABLE "MoveNode" DROP COLUMN IF EXISTS "currentStreak";
ALTER TABLE "MoveNode" DROP COLUMN IF EXISTS "lastSeenAt";
