import { FastifyInstance } from 'fastify';
import coursesModule from '../modules/courses/courses.routes';
import trainingModule from '../modules/training/training.routes';
import trainingMarathonsModule from '../modules/training-marathons/training-marathons.routes';
import statsModule from '../modules/stats/stats.routes';
import analysisModule from '../modules/analysis/analysis.routes';
import importedGamesModule from '../modules/imported-games/imported-games.routes';
import openingAnalysisBreakdownsModule from '../modules/imported-games/opening-analysis-breakdowns.routes';
import openingStrugglesModule from '../modules/opening-struggles/opening-struggles.routes';
import labModule from '../modules/lab/lab.routes';
import jobsModule from '../modules/jobs/job-run.routes';
import externalAccountsRoutes from './externalAccounts';
import lichessAuthRoutes from './lichessAuth';
import repertoireCoverageModule from '../modules/repertoire-coverage/repertoire-coverage.routes';
import mcpModule from '../modules/mcp/mcp.routes';
import boardImagesModule from '../modules/board-images/board-images.routes';
import scenarioTrainingModule from '../modules/scenario-training/scenario-training.routes';
import mobileSyncModule from '../modules/mobile-sync/mobile-sync.routes';
import mastersExplorerModule from '../modules/masters-explorer/masters-explorer.routes';

export default function registerRoutes(app: FastifyInstance): void {
  app.register(coursesModule);
  app.register(trainingModule);
  app.register(trainingMarathonsModule);
  app.register(statsModule);
  app.register(analysisModule);
  app.register(importedGamesModule);
  app.register(openingAnalysisBreakdownsModule);
  app.register(openingStrugglesModule);
  app.register(labModule);
  app.register(jobsModule);
  app.register(repertoireCoverageModule);
  app.register(mcpModule);
  app.register(boardImagesModule);
  app.register(scenarioTrainingModule);
  app.register(mobileSyncModule);
  app.register(mastersExplorerModule);
  app.register(lichessAuthRoutes);
  app.register(externalAccountsRoutes);
}
