import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import {
  LICHESS_GAMES_SPEED_PRESETS,
  type LichessGamesSpeedPreset,
} from '@chess-trainer/contracts/opening-explorer';
import { defaultLichessGamesClient } from '../modules/opening-explorer/lichess-opening-explorer.client';
import { TRAP_PILOT_DATASET } from '../modules/trap-pilot/trap-pilot.data';
import { TRAP_PILOT_EVIDENCE_BUNDLE } from '../modules/trap-pilot/trap-pilot.evidence.generated';
import type { TrapPilotEvidenceBundle } from '../modules/trap-pilot/trap-pilot.evidence';
import { captureTrapPopulationEvidence } from '../modules/trap-pilot/trap-pilot.population-evidence';

const OUTPUT_FILE = resolve(__dirname, '../modules/trap-pilot/trap-pilot.evidence.generated.ts');

function selectedRecordIds(): Set<string> | null {
  const value = process.env['TRAP_PILOT_RECORD_IDS']?.trim();
  if (!value) return null;
  return new Set(value.split(',').map((id) => id.trim()).filter(Boolean));
}

function selectedSpeedPreset(): LichessGamesSpeedPreset {
  const value = process.env['TRAP_PILOT_SPEED_PRESET']?.trim() || 'BLITZ_AND_SLOWER';
  if (!LICHESS_GAMES_SPEED_PRESETS.includes(value as LichessGamesSpeedPreset)) {
    throw new Error(`Unsupported TRAP_PILOT_SPEED_PRESET ${value}.`);
  }
  return value as LichessGamesSpeedPreset;
}

function renderBundle(bundle: TrapPilotEvidenceBundle): string {
  return `// Generated trap-pilot evidence bundle.
// Generated by: npm run traps:refresh-population --workspace=apps/api
// Do not edit evidence payloads manually.

import type { TrapPilotEvidenceBundle } from './trap-pilot.evidence';

export const TRAP_PILOT_EVIDENCE_BUNDLE: TrapPilotEvidenceBundle = ${JSON.stringify(bundle, null, 2)};
`;
}

async function main(): Promise<void> {
  if (process.env['TRAP_PILOT_REFRESH_POPULATION'] !== '1') {
    throw new Error('Set TRAP_PILOT_REFRESH_POPULATION=1 to run the opt-in population evidence refresh.');
  }
  const accessToken = process.env['TRAP_PILOT_LICHESS_TOKEN']?.trim();
  if (!accessToken) throw new Error('TRAP_PILOT_LICHESS_TOKEN is required.');

  const requestedIds = selectedRecordIds();
  const records = requestedIds
    ? TRAP_PILOT_DATASET.records.filter((record) => requestedIds.has(record.id))
    : [...TRAP_PILOT_DATASET.records];
  if (requestedIds) {
    const foundIds = new Set(records.map((record) => record.id));
    const unknown = [...requestedIds].filter((id) => !foundIds.has(id));
    if (unknown.length) throw new Error(`Unknown trap record ids: ${unknown.join(', ')}`);
  }
  if (!records.length) throw new Error('No trap records selected for population evidence refresh.');

  const speedPreset = selectedSpeedPreset();
  const refreshed = [];
  for (const record of records) {
    const snapshot = await captureTrapPopulationEvidence({
      record,
      speedPreset,
      accessToken,
      client: defaultLichessGamesClient,
    });
    refreshed.push(snapshot);
    console.log(`Refreshed ${speedPreset} population evidence for ${record.id} (${snapshot.games.total} games).`);
  }

  const refreshedKeys = new Set(refreshed.map(
    (snapshot) => `${snapshot.recordId}:${snapshot.profile.version}:${snapshot.profile.speedPreset}`,
  ));
  const bundle: TrapPilotEvidenceBundle = {
    schemaVersion: 1,
    datasetVersion: TRAP_PILOT_DATASET.datasetVersion,
    engineSnapshots: TRAP_PILOT_EVIDENCE_BUNDLE.engineSnapshots,
    populationSnapshots: [
      ...TRAP_PILOT_EVIDENCE_BUNDLE.populationSnapshots.filter(
        (snapshot) => !refreshedKeys.has(`${snapshot.recordId}:${snapshot.profile.version}:${snapshot.profile.speedPreset}`),
      ),
      ...refreshed,
    ].sort((left, right) => (
      left.recordId.localeCompare(right.recordId)
      || left.profile.version.localeCompare(right.profile.version)
      || left.profile.speedPreset.localeCompare(right.profile.speedPreset)
    )),
  };

  await mkdir(dirname(OUTPUT_FILE), { recursive: true });
  await writeFile(OUTPUT_FILE, renderBundle(bundle), 'utf8');
  console.log(`Wrote ${refreshed.length} population snapshots to ${OUTPUT_FILE}.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
