import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { getLocalBatchStockfishAnalysisConfig } from '../modules/analysis/batch-analysis.config';
import { createStockfishEngine } from '../modules/analysis/stockfish-engine.factory';
import { deriveTrapEngineAnalysisTargets } from '../modules/trap-pilot/trap-pilot.analysis-targets';
import { TRAP_PILOT_DATASET } from '../modules/trap-pilot/trap-pilot.data';
import { TRAP_PILOT_EVIDENCE_BUNDLE } from '../modules/trap-pilot/trap-pilot.evidence.generated';
import {
  type TrapEngineEvidenceSnapshot,
  type TrapPilotEvidenceBundle,
  withEngineEvidenceHash,
} from '../modules/trap-pilot/trap-pilot.evidence';
import { deriveTrapOccurrenceIdentity } from '../modules/trap-pilot/trap-pilot.validator';

const OUTPUT_FILE = resolve(__dirname, '../modules/trap-pilot/trap-pilot.evidence.generated.ts');

function positiveInt(value: string | undefined, fallback: number): number {
  if (!value) return fallback;
  const parsed = Number.parseInt(value, 10);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : fallback;
}

function selectedRecordIds(): Set<string> | null {
  const value = process.env['TRAP_PILOT_RECORD_IDS']?.trim();
  if (!value) return null;
  return new Set(value.split(',').map((id) => id.trim()).filter(Boolean));
}

function renderBundle(bundle: TrapPilotEvidenceBundle): string {
  return `// Generated trap-pilot evidence bundle.
// Generated by: npm run traps:refresh-engine --workspace=apps/api
// Do not edit evidence payloads manually.

import type { TrapPilotEvidenceBundle } from './trap-pilot.evidence';

export const TRAP_PILOT_EVIDENCE_BUNDLE: TrapPilotEvidenceBundle = ${JSON.stringify(bundle, null, 2)};
`;
}

async function main(): Promise<void> {
  if (process.env['TRAP_PILOT_REFRESH_ENGINE'] !== '1') {
    throw new Error('Set TRAP_PILOT_REFRESH_ENGINE=1 to run the opt-in engine evidence refresh.');
  }

  const baseConfig = getLocalBatchStockfishAnalysisConfig();
  const depth = positiveInt(process.env['TRAP_PILOT_ENGINE_DEPTH'], 24);
  const multipv = Math.min(3, positiveInt(process.env['TRAP_PILOT_ENGINE_MULTIPV'], 3));
  const timeoutMs = positiveInt(process.env['TRAP_PILOT_ENGINE_TIMEOUT_MS'], Math.max(baseConfig.timeoutMs, 120_000));
  const profileVersion = `depth-${depth}-multipv-${multipv}-v1`;
  const engineVersion = process.env['TRAP_PILOT_ENGINE_VERSION']?.trim()
    || (baseConfig.engine === 'wasm' ? 'stockfish-npm@18.0.7' : '');
  if (!engineVersion) {
    throw new Error('TRAP_PILOT_ENGINE_VERSION is required when using an external local Stockfish binary.');
  }

  const requestedIds = selectedRecordIds();
  const records = requestedIds
    ? TRAP_PILOT_DATASET.records.filter((record) => requestedIds.has(record.id))
    : [...TRAP_PILOT_DATASET.records];
  if (requestedIds) {
    const foundIds = new Set(records.map((record) => record.id));
    const unknown = [...requestedIds].filter((id) => !foundIds.has(id));
    if (unknown.length) throw new Error(`Unknown trap record ids: ${unknown.join(', ')}`);
  }
  if (!records.length) throw new Error('No trap records selected for engine evidence refresh.');

  const engine = createStockfishEngine({
    ...baseConfig,
    enabled: true,
    depth,
    multipv,
    timeoutMs,
  });
  const capturedAt = new Date().toISOString();
  const refreshed: TrapEngineEvidenceSnapshot[] = [];

  await engine.init();
  try {
    for (const record of records) {
      const targets = deriveTrapEngineAnalysisTargets(record);
      const analysedTargets = [];
      for (const target of targets) {
        const analysis = await engine.analyzePosition(target.fen, { depth, multipv });
        analysedTargets.push({
          ...target,
          bestMoveUci: analysis.bestMoveUci ?? null,
          bestScoreCpWhite: analysis.bestScoreCpWhite ?? null,
          bestMateWhite: analysis.bestMateWhite ?? null,
          lines: analysis.lines ?? [],
        });
      }
      refreshed.push(withEngineEvidenceHash({
        recordId: record.id,
        occurrenceIdentity: deriveTrapOccurrenceIdentity(record),
        profile: {
          id: 'trap-pilot-stockfish',
          version: profileVersion,
          engine: baseConfig.engine,
          engineVersion,
          depth,
          multipv,
        },
        capturedAt,
        targets: analysedTargets,
      }));
      console.log(`Refreshed engine evidence for ${record.id} (${analysedTargets.length} targets).`);
    }
  } finally {
    engine.dispose();
  }

  const refreshedKeys = new Set(refreshed.map((snapshot) => `${snapshot.recordId}:${snapshot.profile.version}`));
  const bundle: TrapPilotEvidenceBundle = {
    schemaVersion: 1,
    datasetVersion: TRAP_PILOT_DATASET.datasetVersion,
    engineSnapshots: [
      ...TRAP_PILOT_EVIDENCE_BUNDLE.engineSnapshots.filter(
        (snapshot) => !refreshedKeys.has(`${snapshot.recordId}:${snapshot.profile.version}`),
      ),
      ...refreshed,
    ].sort((left, right) => left.recordId.localeCompare(right.recordId) || left.profile.version.localeCompare(right.profile.version)),
    populationSnapshots: TRAP_PILOT_EVIDENCE_BUNDLE.populationSnapshots,
  };

  await mkdir(dirname(OUTPUT_FILE), { recursive: true });
  await writeFile(OUTPUT_FILE, renderBundle(bundle), 'utf8');
  console.log(`Wrote ${refreshed.length} engine snapshots to ${OUTPUT_FILE}.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
