import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { Chess } from 'chess.js';
import { normalizeFenForPosition } from 'chess-domain';
import type { OpeningBookEntry } from '../services/opening-book/openingBook.types';

const SOURCE_REPOSITORY = 'https://github.com/lichess-org/chess-openings';
const SOURCE_COMMIT = '51a55d956b7ed0b9cd7853893744b1ca39cd2a05';
const SOURCE_FILES = ['a.tsv', 'b.tsv', 'c.tsv', 'd.tsv', 'e.tsv'] as const;
const REQUIRED_SOURCE_COLUMNS = ['eco', 'name', 'pgn'] as const;
const OUTPUT_FILE = resolve(__dirname, '../services/opening-book/openingBook.generated.ts');

function parseTsvLine(line: string): string[] {
  return line.replace(/\r$/, '').split('\t');
}

function assertRequiredColumns(headers: string[], file: string): Map<string, number> {
  const index = new Map(headers.map((header, idx) => [header, idx]));
  const missing = REQUIRED_SOURCE_COLUMNS.filter((column) => !index.has(column));
  if (missing.length > 0) throw new Error(`${file} missing required columns: ${missing.join(', ')}`);
  return index;
}

function valueAt(values: string[], columns: Map<string, number>, column: (typeof REQUIRED_SOURCE_COLUMNS)[number]): string {
  return values[columns.get(column) ?? -1]?.trim() ?? '';
}

function deriveMoveData(file: string, lineNumber: number, pgn: string): Pick<OpeningBookEntry, 'uci' | 'epd' | 'ply'> {
  const chess = new Chess();
  try {
    chess.loadPgn(pgn, { strict: false });
  } catch (error: any) {
    throw new Error(`${file}:${lineNumber} could not parse PGN "${pgn}": ${error?.message ?? String(error)}`);
  }

  const moves = chess.history({ verbose: true });
  if (moves.length === 0) throw new Error(`${file}:${lineNumber} has no playable moves`);

  return {
    uci: moves.map((move) => `${move.from}${move.to}${move.promotion ?? ''}`).join(' '),
    epd: normalizeFenForPosition(chess.fen()),
    ply: moves.length,
  };
}

function parseTsv(file: string, content: string): OpeningBookEntry[] {
  const lines = content.split('\n').filter((line) => line.trim().length > 0);
  if (lines.length === 0) return [];

  const headers = parseTsvLine(lines[0]).map((header) => header.trim());
  const columns = assertRequiredColumns(headers, file);

  return lines.slice(1).map((line, idx) => {
    const lineNumber = idx + 2;
    const values = parseTsvLine(line);
    const entry = {
      eco: valueAt(values, columns, 'eco'),
      name: valueAt(values, columns, 'name'),
      pgn: valueAt(values, columns, 'pgn'),
    };
    const missing = REQUIRED_SOURCE_COLUMNS.filter((column) => !entry[column]);
    if (missing.length > 0) {
      throw new Error(`${file}:${lineNumber} missing required values: ${missing.join(', ')}`);
    }

    return {
      ...entry,
      ...deriveMoveData(file, lineNumber, entry.pgn),
    };
  });
}

function sortOpeningBook(entries: OpeningBookEntry[]): OpeningBookEntry[] {
  return entries.slice().sort((a, b) => a.eco.localeCompare(b.eco) || a.ply - b.ply || a.name.localeCompare(b.name) || a.epd.localeCompare(b.epd));
}

function renderGeneratedFile(entries: OpeningBookEntry[]): string {
  return `// Generated opening book data.
// Source: ${SOURCE_REPOSITORY}
// Source commit: ${SOURCE_COMMIT}
// Source files: ${SOURCE_FILES.join(', ')}
// Derived fields: uci, epd, ply are generated by replaying source PGN with chess.js
// License: CC0/public domain
// Regenerate with: npm run opening-book:update --workspace=apps/api
// Do not edit manually.

import type { OpeningBookEntry } from './openingBook.types';

export const OPENING_BOOK: readonly OpeningBookEntry[] = ${JSON.stringify(entries, null, 2)};
`;
}

async function fetchSourceFile(file: string): Promise<string> {
  const url = `https://raw.githubusercontent.com/lichess-org/chess-openings/${SOURCE_COMMIT}/${file}`;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  return response.text();
}

async function main(): Promise<void> {
  const entries: OpeningBookEntry[] = [];
  for (const file of SOURCE_FILES) {
    const content = await fetchSourceFile(file);
    entries.push(...parseTsv(file, content));
  }

  const sorted = sortOpeningBook(entries);
  await mkdir(dirname(OUTPUT_FILE), { recursive: true });
  await writeFile(OUTPUT_FILE, renderGeneratedFile(sorted), 'utf8');
  console.log(`Wrote ${sorted.length} openings to ${OUTPUT_FILE}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
